// Generated by scripts/generate_blueprint_next_icons.py from pinned Blueprint /next assets. DO NOT EDIT.
package io.github.joelromanpr.brace.blueprinticonsnext

import io.github.joelromanpr.brace.icons.BraceIconName

/** Typed names for all 695 canonical glyphs in pinned @blueprintjs/icons/next. */
public object BraceBlueprintNextIconNames {
    public val Airplane: BraceIconName = BraceIconName("airplane")
    public val AlignBottom: BraceIconName = BraceIconName("align-bottom")
    public val AlignHorizontalCenter: BraceIconName = BraceIconName("align-horizontal-center")
    public val AlignLeft: BraceIconName = BraceIconName("align-left")
    public val AlignRight: BraceIconName = BraceIconName("align-right")
    public val AlignTop: BraceIconName = BraceIconName("align-top")
    public val AlignVerticalCenter: BraceIconName = BraceIconName("align-vertical-center")
    public val Ammunition: BraceIconName = BraceIconName("ammunition")
    public val Anchor: BraceIconName = BraceIconName("anchor")
    public val Antenna: BraceIconName = BraceIconName("antenna")
    public val Application: BraceIconName = BraceIconName("application")
    public val ApplicationArrowIn: BraceIconName = BraceIconName("application-arrow-in")
    public val ApplicationH: BraceIconName = BraceIconName("application-h")
    public val ApplicationPlus: BraceIconName = BraceIconName("application-plus")
    public val Applications: BraceIconName = BraceIconName("applications")
    public val Array: BraceIconName = BraceIconName("array")
    public val ArrayBoolean: BraceIconName = BraceIconName("array-boolean")
    public val ArrayDate: BraceIconName = BraceIconName("array-date")
    public val ArrayFloatingPoint: BraceIconName = BraceIconName("array-floating-point")
    public val ArrayNumeric: BraceIconName = BraceIconName("array-numeric")
    public val ArrayObject: BraceIconName = BraceIconName("array-object")
    public val ArrayString: BraceIconName = BraceIconName("array-string")
    public val ArrayTimestamp: BraceIconName = BraceIconName("array-timestamp")
    public val ArrowArcLeft: BraceIconName = BraceIconName("arrow-arc-left")
    public val ArrowArcRight: BraceIconName = BraceIconName("arrow-arc-right")
    public val ArrowBetweenBrackets: BraceIconName = BraceIconName("arrow-between-brackets")
    public val ArrowBetweenDots: BraceIconName = BraceIconName("arrow-between-dots")
    public val ArrowCcw: BraceIconName = BraceIconName("arrow-ccw")
    public val ArrowCcwCheck: BraceIconName = BraceIconName("arrow-ccw-check")
    public val ArrowCcwClock: BraceIconName = BraceIconName("arrow-ccw-clock")
    public val ArrowCcwExclamation: BraceIconName = BraceIconName("arrow-ccw-exclamation")
    public val ArrowCcwPlayHistory: BraceIconName = BraceIconName("arrow-ccw-play-history")
    public val ArrowCircleDownRight: BraceIconName = BraceIconName("arrow-circle-down-right")
    public val ArrowCw: BraceIconName = BraceIconName("arrow-cw")
    public val ArrowDoubleFromDot: BraceIconName = BraceIconName("arrow-double-from-dot")
    public val ArrowDown: BraceIconName = BraceIconName("arrow-down")
    public val ArrowDownAZ: BraceIconName = BraceIconName("arrow-down-a-z")
    public val ArrowDownFromLines: BraceIconName = BraceIconName("arrow-down-from-lines")
    public val ArrowDownLeft: BraceIconName = BraceIconName("arrow-down-left")
    public val ArrowDownNineOne: BraceIconName = BraceIconName("arrow-down-nine-one")
    public val ArrowDownOneNine: BraceIconName = BraceIconName("arrow-down-one-nine")
    public val ArrowDownRight: BraceIconName = BraceIconName("arrow-down-right")
    public val ArrowDownToTray: BraceIconName = BraceIconName("arrow-down-to-tray")
    public val ArrowDownZA: BraceIconName = BraceIconName("arrow-down-z-a")
    public val ArrowLeft: BraceIconName = BraceIconName("arrow-left")
    public val ArrowMerge: BraceIconName = BraceIconName("arrow-merge")
    public val ArrowRight: BraceIconName = BraceIconName("arrow-right")
    public val ArrowRightFromArc: BraceIconName = BraceIconName("arrow-right-from-arc")
    public val ArrowRightFromBracket: BraceIconName = BraceIconName("arrow-right-from-bracket")
    public val ArrowRightToArc: BraceIconName = BraceIconName("arrow-right-to-arc")
    public val ArrowRightToBracket: BraceIconName = BraceIconName("arrow-right-to-bracket")
    public val ArrowSplit: BraceIconName = BraceIconName("arrow-split")
    public val ArrowThroughDot: BraceIconName = BraceIconName("arrow-through-dot")
    public val ArrowToDot: BraceIconName = BraceIconName("arrow-to-dot")
    public val ArrowTrendDown: BraceIconName = BraceIconName("arrow-trend-down")
    public val ArrowTrendUp: BraceIconName = BraceIconName("arrow-trend-up")
    public val ArrowTurnBottomLeft: BraceIconName = BraceIconName("arrow-turn-bottom-left")
    public val ArrowTurnBottomRight: BraceIconName = BraceIconName("arrow-turn-bottom-right")
    public val ArrowUp: BraceIconName = BraceIconName("arrow-up")
    public val ArrowUpFromLines: BraceIconName = BraceIconName("arrow-up-from-lines")
    public val ArrowUpFromTray: BraceIconName = BraceIconName("arrow-up-from-tray")
    public val ArrowUpLeft: BraceIconName = BraceIconName("arrow-up-left")
    public val ArrowUpRight: BraceIconName = BraceIconName("arrow-up-right")
    public val ArrowsBranchFromDot: BraceIconName = BraceIconName("arrows-branch-from-dot")
    public val ArrowsCcwCheck: BraceIconName = BraceIconName("arrows-ccw-check")
    public val ArrowsCw: BraceIconName = BraceIconName("arrows-cw")
    public val ArrowsCwSlash: BraceIconName = BraceIconName("arrows-cw-slash")
    public val ArrowsDownUp: BraceIconName = BraceIconName("arrows-down-up")
    public val ArrowsHorizontal: BraceIconName = BraceIconName("arrows-horizontal")
    public val ArrowsInDiagonal: BraceIconName = BraceIconName("arrows-in-diagonal")
    public val ArrowsLeftRight: BraceIconName = BraceIconName("arrows-left-right")
    public val ArrowsMultiFromDot: BraceIconName = BraceIconName("arrows-multi-from-dot")
    public val ArrowsOutCardinal: BraceIconName = BraceIconName("arrows-out-cardinal")
    public val ArrowsOutCorners: BraceIconName = BraceIconName("arrows-out-corners")
    public val ArrowsOutDiagonal: BraceIconName = BraceIconName("arrows-out-diagonal")
    public val ArrowsShuffle: BraceIconName = BraceIconName("arrows-shuffle")
    public val ArrowsSpin: BraceIconName = BraceIconName("arrows-spin")
    public val ArrowsUpArcRight: BraceIconName = BraceIconName("arrows-up-arc-right")
    public val ArrowsUpDownLine: BraceIconName = BraceIconName("arrows-up-down-line")
    public val ArrowsVertical: BraceIconName = BraceIconName("arrows-vertical")
    public val Asterisk: BraceIconName = BraceIconName("asterisk")
    public val At: BraceIconName = BraceIconName("at")
    public val Axle: BraceIconName = BraceIconName("axle")
    public val BackwardTen: BraceIconName = BraceIconName("backward-ten")
    public val BadgeCheck: BraceIconName = BraceIconName("badge-check")
    public val BarcodeRead: BraceIconName = BraceIconName("barcode-read")
    public val Barricade: BraceIconName = BraceIconName("barricade")
    public val BarsAscending: BraceIconName = BraceIconName("bars-ascending")
    public val BarsDescending: BraceIconName = BraceIconName("bars-descending")
    public val BarsHorizontalAscending: BraceIconName = BraceIconName("bars-horizontal-ascending")
    public val BarsHorizontalDescending: BraceIconName = BraceIconName("bars-horizontal-descending")
    public val Bell: BraceIconName = BraceIconName("bell")
    public val BellCheck: BraceIconName = BraceIconName("bell-check")
    public val BellPlus: BraceIconName = BraceIconName("bell-plus")
    public val BellZ: BraceIconName = BraceIconName("bell-z")
    public val Binary: BraceIconName = BraceIconName("binary")
    public val Blank: BraceIconName = BraceIconName("blank")
    public val BlockDoubleChevronRight: BraceIconName = BraceIconName("block-double-chevron-right")
    public val Book: BraceIconName = BraceIconName("book")
    public val BookArrowUp: BraceIconName = BraceIconName("book-arrow-up")
    public val BookBookmark: BraceIconName = BraceIconName("book-bookmark")
    public val BookOpen: BraceIconName = BraceIconName("book-open")
    public val Bookmark: BraceIconName = BraceIconName("bookmark")
    public val Box: BraceIconName = BraceIconName("box")
    public val BoxArrowDown: BraceIconName = BraceIconName("box-arrow-down")
    public val BoxArrowUp: BraceIconName = BraceIconName("box-arrow-up")
    public val Brain: BraceIconName = BraceIconName("brain")
    public val Briefcase: BraceIconName = BraceIconName("briefcase")
    public val Broom: BraceIconName = BraceIconName("broom")
    public val Bug: BraceIconName = BraceIconName("bug")
    public val Buggy: BraceIconName = BraceIconName("buggy")
    public val Building: BraceIconName = BraceIconName("building")
    public val Bullseye: BraceIconName = BraceIconName("bullseye")
    public val CabinetFiling: BraceIconName = BraceIconName("cabinet-filing")
    public val Calculator: BraceIconName = BraceIconName("calculator")
    public val Calendar: BraceIconName = BraceIconName("calendar")
    public val CalendarDots: BraceIconName = BraceIconName("calendar-dots")
    public val Camera: BraceIconName = BraceIconName("camera")
    public val Capsule: BraceIconName = BraceIconName("capsule")
    public val Car: BraceIconName = BraceIconName("car")
    public val CarCheck: BraceIconName = BraceIconName("car-check")
    public val CarQuestion: BraceIconName = BraceIconName("car-question")
    public val CaretDown: BraceIconName = BraceIconName("caret-down")
    public val CaretLeft: BraceIconName = BraceIconName("caret-left")
    public val CaretRight: BraceIconName = BraceIconName("caret-right")
    public val CaretUp: BraceIconName = BraceIconName("caret-up")
    public val CaretsHorizontal: BraceIconName = BraceIconName("carets-horizontal")
    public val CaretsVertical: BraceIconName = BraceIconName("carets-vertical")
    public val CargoShip: BraceIconName = BraceIconName("cargo-ship")
    public val Cart: BraceIconName = BraceIconName("cart")
    public val CellTower: BraceIconName = BraceIconName("cell-tower")
    public val CellTowerMagnifyingGlass: BraceIconName = BraceIconName("cell-tower-magnifying-glass")
    public val ChartArea: BraceIconName = BraceIconName("chart-area")
    public val ChartBar: BraceIconName = BraceIconName("chart-bar")
    public val ChartBarGrouped: BraceIconName = BraceIconName("chart-bar-grouped")
    public val ChartBarHorizontal: BraceIconName = BraceIconName("chart-bar-horizontal")
    public val ChartCurvedRange: BraceIconName = BraceIconName("chart-curved-range")
    public val ChartDoughnut: BraceIconName = BraceIconName("chart-doughnut")
    public val ChartGantt: BraceIconName = BraceIconName("chart-gantt")
    public val ChartLine: BraceIconName = BraceIconName("chart-line")
    public val ChartLineArrowRight: BraceIconName = BraceIconName("chart-line-arrow-right")
    public val ChartLineFunnel: BraceIconName = BraceIconName("chart-line-funnel")
    public val ChartLineGear: BraceIconName = BraceIconName("chart-line-gear")
    public val ChartLineMagnifyingGlass: BraceIconName = BraceIconName("chart-line-magnifying-glass")
    public val ChartLinePlus: BraceIconName = BraceIconName("chart-line-plus")
    public val ChartPie: BraceIconName = BraceIconName("chart-pie")
    public val ChartRegression: BraceIconName = BraceIconName("chart-regression")
    public val ChartScatter: BraceIconName = BraceIconName("chart-scatter")
    public val ChartStackedBar: BraceIconName = BraceIconName("chart-stacked-bar")
    public val ChartStackedBarFull: BraceIconName = BraceIconName("chart-stacked-bar-full")
    public val ChartStep: BraceIconName = BraceIconName("chart-step")
    public val ChartTrendUp: BraceIconName = BraceIconName("chart-trend-up")
    public val ChartWaterfall: BraceIconName = BraceIconName("chart-waterfall")
    public val ChatDots: BraceIconName = BraceIconName("chat-dots")
    public val ChatDotsPlus: BraceIconName = BraceIconName("chat-dots-plus")
    public val ChatTeardropLightning: BraceIconName = BraceIconName("chat-teardrop-lightning")
    public val Chats: BraceIconName = BraceIconName("chats")
    public val Check: BraceIconName = BraceIconName("check")
    public val CheckSmall: BraceIconName = BraceIconName("check-small")
    public val ChevronDown: BraceIconName = BraceIconName("chevron-down")
    public val ChevronLeft: BraceIconName = BraceIconName("chevron-left")
    public val ChevronLineLeft: BraceIconName = BraceIconName("chevron-line-left")
    public val ChevronLineRight: BraceIconName = BraceIconName("chevron-line-right")
    public val ChevronRight: BraceIconName = BraceIconName("chevron-right")
    public val ChevronUp: BraceIconName = BraceIconName("chevron-up")
    public val ChevronsHorizontalBetween: BraceIconName = BraceIconName("chevrons-horizontal-between")
    public val ChevronsIn: BraceIconName = BraceIconName("chevrons-in")
    public val ChevronsOut: BraceIconName = BraceIconName("chevrons-out")
    public val ChevronsVerticalBetween: BraceIconName = BraceIconName("chevrons-vertical-between")
    public val Circle: BraceIconName = BraceIconName("circle")
    public val CircleArrowDown: BraceIconName = BraceIconName("circle-arrow-down")
    public val CircleArrowLeft: BraceIconName = BraceIconName("circle-arrow-left")
    public val CircleArrowOut: BraceIconName = BraceIconName("circle-arrow-out")
    public val CircleArrowRight: BraceIconName = BraceIconName("circle-arrow-right")
    public val CircleArrowUp: BraceIconName = BraceIconName("circle-arrow-up")
    public val CircleCheck: BraceIconName = BraceIconName("circle-check")
    public val CircleCheckAlt: BraceIconName = BraceIconName("circle-check-alt")
    public val CircleCrosshairs: BraceIconName = BraceIconName("circle-crosshairs")
    public val CircleCrosshairsDots: BraceIconName = BraceIconName("circle-crosshairs-dots")
    public val CircleDashed: BraceIconName = BraceIconName("circle-dashed")
    public val CircleDashedRing: BraceIconName = BraceIconName("circle-dashed-ring")
    public val CircleDot: BraceIconName = BraceIconName("circle-dot")
    public val CircleDotPlus: BraceIconName = BraceIconName("circle-dot-plus")
    public val CircleExclamation: BraceIconName = BraceIconName("circle-exclamation")
    public val CircleExclamationCheck: BraceIconName = BraceIconName("circle-exclamation-check")
    public val CircleExclamationPlus: BraceIconName = BraceIconName("circle-exclamation-plus")
    public val CircleHalf: BraceIconName = BraceIconName("circle-half")
    public val CircleInfo: BraceIconName = BraceIconName("circle-info")
    public val CircleInfoSmall: BraceIconName = BraceIconName("circle-info-small")
    public val CircleLightning: BraceIconName = BraceIconName("circle-lightning")
    public val CircleMinus: BraceIconName = BraceIconName("circle-minus")
    public val CirclePlus: BraceIconName = BraceIconName("circle-plus")
    public val CirclePlusAlt: BraceIconName = BraceIconName("circle-plus-alt")
    public val CircleQuestion: BraceIconName = BraceIconName("circle-question")
    public val CircleRing: BraceIconName = BraceIconName("circle-ring")
    public val CircleSlash: BraceIconName = BraceIconName("circle-slash")
    public val CircleX: BraceIconName = BraceIconName("circle-x")
    public val CircleXAlt: BraceIconName = BraceIconName("circle-x-alt")
    public val Clipboard: BraceIconName = BraceIconName("clipboard")
    public val ClipboardFile: BraceIconName = BraceIconName("clipboard-file")
    public val ClipboardVariable: BraceIconName = BraceIconName("clipboard-variable")
    public val Clock: BraceIconName = BraceIconName("clock")
    public val ClockLocationPin: BraceIconName = BraceIconName("clock-location-pin")
    public val Cloud: BraceIconName = BraceIconName("cloud")
    public val CloudArrowDown: BraceIconName = BraceIconName("cloud-arrow-down")
    public val CloudArrowUp: BraceIconName = BraceIconName("cloud-arrow-up")
    public val CloudCheck: BraceIconName = BraceIconName("cloud-check")
    public val CloudRain: BraceIconName = BraceIconName("cloud-rain")
    public val Code: BraceIconName = BraceIconName("code")
    public val CodeBlock: BraceIconName = BraceIconName("code-block")
    public val ColumnArrowLeft: BraceIconName = BraceIconName("column-arrow-left")
    public val ColumnArrowRight: BraceIconName = BraceIconName("column-arrow-right")
    public val ColumnCaretLeft: BraceIconName = BraceIconName("column-caret-left")
    public val ColumnsLayout: BraceIconName = BraceIconName("columns-layout")
    public val ColumnsMerge: BraceIconName = BraceIconName("columns-merge")
    public val ColumnsMinusLeft: BraceIconName = BraceIconName("columns-minus-left")
    public val ColumnsPlusLeft: BraceIconName = BraceIconName("columns-plus-left")
    public val ColumnsPlusRight: BraceIconName = BraceIconName("columns-plus-right")
    public val ColumnsSplit: BraceIconName = BraceIconName("columns-split")
    public val ColumnsThree: BraceIconName = BraceIconName("columns-three")
    public val ColumnsTwo: BraceIconName = BraceIconName("columns-two")
    public val ColumnsTwoCaretRight: BraceIconName = BraceIconName("columns-two-caret-right")
    public val ColumnsXLeft: BraceIconName = BraceIconName("columns-x-left")
    public val ColumnsXRight: BraceIconName = BraceIconName("columns-x-right")
    public val Comparison: BraceIconName = BraceIconName("comparison")
    public val Compass: BraceIconName = BraceIconName("compass")
    public val Copy: BraceIconName = BraceIconName("copy")
    public val CreditCard: BraceIconName = BraceIconName("credit-card")
    public val Crop: BraceIconName = BraceIconName("crop")
    public val Crown: BraceIconName = BraceIconName("crown")
    public val CrystalBall: BraceIconName = BraceIconName("crystal-ball")
    public val Cube: BraceIconName = BraceIconName("cube")
    public val CubeCutout: BraceIconName = BraceIconName("cube-cutout")
    public val CubeCutouts: BraceIconName = BraceIconName("cube-cutouts")
    public val CubeMinus: BraceIconName = BraceIconName("cube-minus")
    public val CubePen: BraceIconName = BraceIconName("cube-pen")
    public val CubePlus: BraceIconName = BraceIconName("cube-plus")
    public val Cubes: BraceIconName = BraceIconName("cubes")
    public val CurlyBraces: BraceIconName = BraceIconName("curly-braces")
    public val CurrencyDollar: BraceIconName = BraceIconName("currency-dollar")
    public val CurrencyEuro: BraceIconName = BraceIconName("currency-euro")
    public val CurrencyPound: BraceIconName = BraceIconName("currency-pound")
    public val CurrencyWon: BraceIconName = BraceIconName("currency-won")
    public val CurrencyYen: BraceIconName = BraceIconName("currency-yen")
    public val CursorSelection: BraceIconName = BraceIconName("cursor-selection")
    public val CursorTextSelect: BraceIconName = BraceIconName("cursor-text-select")
    public val CurvedArea: BraceIconName = BraceIconName("curved-area")
    public val Database: BraceIconName = BraceIconName("database")
    public val DatabaseArrowsCw: BraceIconName = BraceIconName("database-arrows-cw")
    public val DatabaseCloud: BraceIconName = BraceIconName("database-cloud")
    public val DatabaseLightning: BraceIconName = BraceIconName("database-lightning")
    public val DatabaseMagnifyingGlass: BraceIconName = BraceIconName("database-magnifying-glass")
    public val DecimalNumber: BraceIconName = BraceIconName("decimal-number")
    public val Delta: BraceIconName = BraceIconName("delta")
    public val DiagramLineage: BraceIconName = BraceIconName("diagram-lineage")
    public val DiagramTree: BraceIconName = BraceIconName("diagram-tree")
    public val DigitsOneTwoThree: BraceIconName = BraceIconName("digits-one-two-three")
    public val DistributeHorizontal: BraceIconName = BraceIconName("distribute-horizontal")
    public val DistributeVertical: BraceIconName = BraceIconName("distribute-vertical")
    public val Divide: BraceIconName = BraceIconName("divide")
    public val Dot: BraceIconName = BraceIconName("dot")
    public val DotsArrowDownLine: BraceIconName = BraceIconName("dots-arrow-down-line")
    public val DotsGridHorizontal: BraceIconName = BraceIconName("dots-grid-horizontal")
    public val DotsGridVertical: BraceIconName = BraceIconName("dots-grid-vertical")
    public val DotsThree: BraceIconName = BraceIconName("dots-three")
    public val DoubleChevronDown: BraceIconName = BraceIconName("double-chevron-down")
    public val DoubleChevronLeft: BraceIconName = BraceIconName("double-chevron-left")
    public val DoubleChevronRight: BraceIconName = BraceIconName("double-chevron-right")
    public val DoubleChevronUp: BraceIconName = BraceIconName("double-chevron-up")
    public val Drone: BraceIconName = BraceIconName("drone")
    public val DroneUav: BraceIconName = BraceIconName("drone-uav")
    public val Droplet: BraceIconName = BraceIconName("droplet")
    public val Earth: BraceIconName = BraceIconName("earth")
    public val EarthMagnifyingGlass: BraceIconName = BraceIconName("earth-magnifying-glass")
    public val Easel: BraceIconName = BraceIconName("easel")
    public val Eject: BraceIconName = BraceIconName("eject")
    public val Envelope: BraceIconName = BraceIconName("envelope")
    public val Equals: BraceIconName = BraceIconName("equals")
    public val Eraser: BraceIconName = BraceIconName("eraser")
    public val Excavator: BraceIconName = BraceIconName("excavator")
    public val Exclamation: BraceIconName = BraceIconName("exclamation")
    public val Eye: BraceIconName = BraceIconName("eye")
    public val EyeCheck: BraceIconName = BraceIconName("eye-check")
    public val EyeSlash: BraceIconName = BraceIconName("eye-slash")
    public val FaceSmile: BraceIconName = BraceIconName("face-smile")
    public val FastBackward: BraceIconName = BraceIconName("fast-backward")
    public val FastForward: BraceIconName = BraceIconName("fast-forward")
    public val FighterJet: BraceIconName = BraceIconName("fighter-jet")
    public val File: BraceIconName = BraceIconName("file")
    public val FileArrowIn: BraceIconName = BraceIconName("file-arrow-in")
    public val FileArrowOut: BraceIconName = BraceIconName("file-arrow-out")
    public val FileCheck: BraceIconName = BraceIconName("file-check")
    public val FileCode: BraceIconName = BraceIconName("file-code")
    public val FileCss: BraceIconName = BraceIconName("file-css")
    public val FileLines: BraceIconName = BraceIconName("file-lines")
    public val FileLock: BraceIconName = BraceIconName("file-lock")
    public val FileRotateLeft: BraceIconName = BraceIconName("file-rotate-left")
    public val Film: BraceIconName = BraceIconName("film")
    public val Flag: BraceIconName = BraceIconName("flag")
    public val Flame: BraceIconName = BraceIconName("flame")
    public val Flashlight: BraceIconName = BraceIconName("flashlight")
    public val Flask: BraceIconName = BraceIconName("flask")
    public val FloppyDisk: BraceIconName = BraceIconName("floppy-disk")
    public val Folder: BraceIconName = BraceIconName("folder")
    public val FolderArrowIn: BraceIconName = BraceIconName("folder-arrow-in")
    public val FolderArrowOut: BraceIconName = BraceIconName("folder-arrow-out")
    public val FolderOpen: BraceIconName = BraceIconName("folder-open")
    public val FolderOpenArrowOut: BraceIconName = BraceIconName("folder-open-arrow-out")
    public val FolderPlus: BraceIconName = BraceIconName("folder-plus")
    public val FolderRoot: BraceIconName = BraceIconName("folder-root")
    public val Font: BraceIconName = BraceIconName("font")
    public val ForwardTen: BraceIconName = BraceIconName("forward-ten")
    public val FrameCorners: BraceIconName = BraceIconName("frame-corners")
    public val FrameCube: BraceIconName = BraceIconName("frame-cube")
    public val FrameDot: BraceIconName = BraceIconName("frame-dot")
    public val FrameDotPlus: BraceIconName = BraceIconName("frame-dot-plus")
    public val FrameDotX: BraceIconName = BraceIconName("frame-dot-x")
    public val FrameEye: BraceIconName = BraceIconName("frame-eye")
    public val FrameGroupObjects: BraceIconName = BraceIconName("frame-group-objects")
    public val FrameGroupObjectsX: BraceIconName = BraceIconName("frame-group-objects-x")
    public val FrameSquare: BraceIconName = BraceIconName("frame-square")
    public val Function: BraceIconName = BraceIconName("function")
    public val FunctionArrowToColumn: BraceIconName = BraceIconName("function-arrow-to-column")
    public val FunctionArrowUp: BraceIconName = BraceIconName("function-arrow-up")
    public val FunctionMinimal: BraceIconName = BraceIconName("function-minimal")
    public val Funnel: BraceIconName = BraceIconName("funnel")
    public val FunnelArrowDown: BraceIconName = BraceIconName("funnel-arrow-down")
    public val FunnelArrowUp: BraceIconName = BraceIconName("funnel-arrow-up")
    public val FunnelCaretRight: BraceIconName = BraceIconName("funnel-caret-right")
    public val FunnelCheck: BraceIconName = BraceIconName("funnel-check")
    public val FunnelList: BraceIconName = BraceIconName("funnel-list")
    public val FunnelUsers: BraceIconName = BraceIconName("funnel-users")
    public val FunnelX: BraceIconName = BraceIconName("funnel-x")
    public val GasCan: BraceIconName = BraceIconName("gas-can")
    public val Gauge: BraceIconName = BraceIconName("gauge")
    public val Gavel: BraceIconName = BraceIconName("gavel")
    public val Gear: BraceIconName = BraceIconName("gear")
    public val Gift: BraceIconName = BraceIconName("gift")
    public val GitBranch: BraceIconName = BraceIconName("git-branch")
    public val GitBranchLock: BraceIconName = BraceIconName("git-branch-lock")
    public val GitBranchLockOpen: BraceIconName = BraceIconName("git-branch-lock-open")
    public val GitBranchPlus: BraceIconName = BraceIconName("git-branch-plus")
    public val GitCommit: BraceIconName = BraceIconName("git-commit")
    public val GitMerge: BraceIconName = BraceIconName("git-merge")
    public val GitPull: BraceIconName = BraceIconName("git-pull")
    public val GitRebase: BraceIconName = BraceIconName("git-rebase")
    public val Globe: BraceIconName = BraceIconName("globe")
    public val GlobePlus: BraceIconName = BraceIconName("globe-plus")
    public val GlobeUsers: BraceIconName = BraceIconName("globe-users")
    public val GraduationCap: BraceIconName = BraceIconName("graduation-cap")
    public val GreaterThan: BraceIconName = BraceIconName("greater-than")
    public val GreaterThanEqual: BraceIconName = BraceIconName("greater-than-equal")
    public val Grid: BraceIconName = BraceIconName("grid")
    public val GridDiamond: BraceIconName = BraceIconName("grid-diamond")
    public val GridHeatmap: BraceIconName = BraceIconName("grid-heatmap")
    public val GridLines: BraceIconName = BraceIconName("grid-lines")
    public val GridPlus: BraceIconName = BraceIconName("grid-plus")
    public val Hammer: BraceIconName = BraceIconName("hammer")
    public val Hand: BraceIconName = BraceIconName("hand")
    public val HandPointDown: BraceIconName = BraceIconName("hand-point-down")
    public val HandPointLeft: BraceIconName = BraceIconName("hand-point-left")
    public val HandPointRight: BraceIconName = BraceIconName("hand-point-right")
    public val HandPointUp: BraceIconName = BraceIconName("hand-point-up")
    public val Hat: BraceIconName = BraceIconName("hat")
    public val Headset: BraceIconName = BraceIconName("headset")
    public val Heart: BraceIconName = BraceIconName("heart")
    public val HeartCrack: BraceIconName = BraceIconName("heart-crack")
    public val Heatmap: BraceIconName = BraceIconName("heatmap")
    public val Helicopter: BraceIconName = BraceIconName("helicopter")
    public val HelperManagement: BraceIconName = BraceIconName("helper-management")
    public val Hexagon: BraceIconName = BraceIconName("hexagon")
    public val HighVoltageUtilityPole: BraceIconName = BraceIconName("high-voltage-utility-pole")
    public val Highlighter: BraceIconName = BraceIconName("highlighter")
    public val House: BraceIconName = BraceIconName("house")
    public val Hurricane: BraceIconName = BraceIconName("hurricane")
    public val IdCard: BraceIconName = BraceIconName("id-card")
    public val Image: BraceIconName = BraceIconName("image")
    public val ImageRotateLeft: BraceIconName = BraceIconName("image-rotate-left")
    public val ImageRotateRight: BraceIconName = BraceIconName("image-rotate-right")
    public val Inbox: BraceIconName = BraceIconName("inbox")
    public val InboxCircle: BraceIconName = BraceIconName("inbox-circle")
    public val InboxFunnel: BraceIconName = BraceIconName("inbox-funnel")
    public val InboxGlobe: BraceIconName = BraceIconName("inbox-globe")
    public val InboxMagnifyingGlass: BraceIconName = BraceIconName("inbox-magnifying-glass")
    public val InnerJoin: BraceIconName = BraceIconName("inner-join")
    public val Intersection: BraceIconName = BraceIconName("intersection")
    public val IpAddress: BraceIconName = BraceIconName("ip-address")
    public val Key: BraceIconName = BraceIconName("key")
    public val KeyBackspace: BraceIconName = BraceIconName("key-backspace")
    public val KeyCommand: BraceIconName = BraceIconName("key-command")
    public val KeyControl: BraceIconName = BraceIconName("key-control")
    public val KeyDelete: BraceIconName = BraceIconName("key-delete")
    public val KeyEscape: BraceIconName = BraceIconName("key-escape")
    public val KeyOption: BraceIconName = BraceIconName("key-option")
    public val KeyShift: BraceIconName = BraceIconName("key-shift")
    public val KeyTab: BraceIconName = BraceIconName("key-tab")
    public val Layer: BraceIconName = BraceIconName("layer")
    public val LayerPlus: BraceIconName = BraceIconName("layer-plus")
    public val Layers: BraceIconName = BraceIconName("layers")
    public val LayersPlus: BraceIconName = BraceIconName("layers-plus")
    public val LayoutBottomRowThreeTiles: BraceIconName = BraceIconName("layout-bottom-row-three-tiles")
    public val LayoutBottomRowTwoTiles: BraceIconName = BraceIconName("layout-bottom-row-two-tiles")
    public val LayoutLeftColumnThreeTiles: BraceIconName = BraceIconName("layout-left-column-three-tiles")
    public val LayoutLeftColumnTwoTiles: BraceIconName = BraceIconName("layout-left-column-two-tiles")
    public val LayoutRightColumnThreeTiles: BraceIconName = BraceIconName("layout-right-column-three-tiles")
    public val LayoutRightColumnTwoTiles: BraceIconName = BraceIconName("layout-right-column-two-tiles")
    public val LayoutTopRowThreeTiles: BraceIconName = BraceIconName("layout-top-row-three-tiles")
    public val LayoutTopRowTwoTiles: BraceIconName = BraceIconName("layout-top-row-two-tiles")
    public val LeftJoin: BraceIconName = BraceIconName("left-join")
    public val LessThan: BraceIconName = BraceIconName("less-than")
    public val LessThanEqual: BraceIconName = BraceIconName("less-than-equal")
    public val LifeRing: BraceIconName = BraceIconName("life-ring")
    public val Lightbulb: BraceIconName = BraceIconName("lightbulb")
    public val Lightning: BraceIconName = BraceIconName("lightning")
    public val LightningBolt: BraceIconName = BraceIconName("lightning-bolt")
    public val Link: BraceIconName = BraceIconName("link")
    public val LinkArrowIn: BraceIconName = BraceIconName("link-arrow-in")
    public val LinkSlash: BraceIconName = BraceIconName("link-slash")
    public val List: BraceIconName = BraceIconName("list")
    public val ListBullets: BraceIconName = BraceIconName("list-bullets")
    public val ListBulletsDetail: BraceIconName = BraceIconName("list-bullets-detail")
    public val ListCaretLeft: BraceIconName = BraceIconName("list-caret-left")
    public val ListCaretRight: BraceIconName = BraceIconName("list-caret-right")
    public val ListChecklist: BraceIconName = BraceIconName("list-checklist")
    public val ListColumns: BraceIconName = BraceIconName("list-columns")
    public val ListFour: BraceIconName = BraceIconName("list-four")
    public val ListNumbers: BraceIconName = BraceIconName("list-numbers")
    public val ListPanel: BraceIconName = BraceIconName("list-panel")
    public val ListPen: BraceIconName = BraceIconName("list-pen")
    public val ListPlus: BraceIconName = BraceIconName("list-plus")
    public val ListSort: BraceIconName = BraceIconName("list-sort")
    public val ListSortAscending: BraceIconName = BraceIconName("list-sort-ascending")
    public val ListSortDescending: BraceIconName = BraceIconName("list-sort-descending")
    public val ListX: BraceIconName = BraceIconName("list-x")
    public val Location: BraceIconName = BraceIconName("location")
    public val LocationPin: BraceIconName = BraceIconName("location-pin")
    public val LocationPinPolygon: BraceIconName = BraceIconName("location-pin-polygon")
    public val Lock: BraceIconName = BraceIconName("lock")
    public val LockOpen: BraceIconName = BraceIconName("lock-open")
    public val Locomotive: BraceIconName = BraceIconName("locomotive")
    public val MagnifyingGlass: BraceIconName = BraceIconName("magnifying-glass")
    public val MagnifyingGlassLines: BraceIconName = BraceIconName("magnifying-glass-lines")
    public val MagnifyingGlassMinus: BraceIconName = BraceIconName("magnifying-glass-minus")
    public val MagnifyingGlassPlus: BraceIconName = BraceIconName("magnifying-glass-plus")
    public val MagnifyingGlassT: BraceIconName = BraceIconName("magnifying-glass-t")
    public val ManyToMany: BraceIconName = BraceIconName("many-to-many")
    public val ManyToOne: BraceIconName = BraceIconName("many-to-one")
    public val Map: BraceIconName = BraceIconName("map")
    public val MapArrowIn: BraceIconName = BraceIconName("map-arrow-in")
    public val MapMagnifyingGlass: BraceIconName = BraceIconName("map-magnifying-glass")
    public val MapPlus: BraceIconName = BraceIconName("map-plus")
    public val Markdown: BraceIconName = BraceIconName("markdown")
    public val Megaphone: BraceIconName = BraceIconName("megaphone")
    public val Microphone: BraceIconName = BraceIconName("microphone")
    public val Minus: BraceIconName = BraceIconName("minus")
    public val MinusSmall: BraceIconName = BraceIconName("minus-small")
    public val MobilePhone: BraceIconName = BraceIconName("mobile-phone")
    public val Monitor: BraceIconName = BraceIconName("monitor")
    public val Moon: BraceIconName = BraceIconName("moon")
    public val Mountain: BraceIconName = BraceIconName("mountain")
    public val Music: BraceIconName = BraceIconName("music")
    public val NavigationArrow: BraceIconName = BraceIconName("navigation-arrow")
    public val NavigationArrowLeft: BraceIconName = BraceIconName("navigation-arrow-left")
    public val NavigationArrowRight: BraceIconName = BraceIconName("navigation-arrow-right")
    public val NetworkHub: BraceIconName = BraceIconName("network-hub")
    public val NodesCircle: BraceIconName = BraceIconName("nodes-circle")
    public val NodesCluster: BraceIconName = BraceIconName("nodes-cluster")
    public val NodesGrid: BraceIconName = BraceIconName("nodes-grid")
    public val NodesGridGroup: BraceIconName = BraceIconName("nodes-grid-group")
    public val NodesGridSkew: BraceIconName = BraceIconName("nodes-grid-skew")
    public val NodesHierarchy: BraceIconName = BraceIconName("nodes-hierarchy")
    public val NodesLinear: BraceIconName = BraceIconName("nodes-linear")
    public val NodesNetwork: BraceIconName = BraceIconName("nodes-network")
    public val NodesNetworkAlt: BraceIconName = BraceIconName("nodes-network-alt")
    public val NodesNetworkArrowIn: BraceIconName = BraceIconName("nodes-network-arrow-in")
    public val NodesNetworkCircle: BraceIconName = BraceIconName("nodes-network-circle")
    public val NodesNetworkLightning: BraceIconName = BraceIconName("nodes-network-lightning")
    public val NodesPolygon: BraceIconName = BraceIconName("nodes-polygon")
    public val NodesSegment: BraceIconName = BraceIconName("nodes-segment")
    public val NodesSquare: BraceIconName = BraceIconName("nodes-square")
    public val NotEqual: BraceIconName = BraceIconName("not-equal")
    public val OilRig: BraceIconName = BraceIconName("oil-rig")
    public val OneToMany: BraceIconName = BraceIconName("one-to-many")
    public val OneToOne: BraceIconName = BraceIconName("one-to-one")
    public val OneToOneExchange: BraceIconName = BraceIconName("one-to-one-exchange")
    public val OneToOneMerge: BraceIconName = BraceIconName("one-to-one-merge")
    public val OneToOnePlus: BraceIconName = BraceIconName("one-to-one-plus")
    public val OuterJoin: BraceIconName = BraceIconName("outer-join")
    public val Package: BraceIconName = BraceIconName("package")
    public val PackageArrowDown: BraceIconName = BraceIconName("package-arrow-down")
    public val PageBreak: BraceIconName = BraceIconName("page-break")
    public val PageLayout: BraceIconName = BraceIconName("page-layout")
    public val PaintBucket: BraceIconName = BraceIconName("paint-bucket")
    public val Paintbrush: BraceIconName = BraceIconName("paintbrush")
    public val PanelLayout: BraceIconName = BraceIconName("panel-layout")
    public val PanelList: BraceIconName = BraceIconName("panel-list")
    public val PanelRight: BraceIconName = BraceIconName("panel-right")
    public val PaperPlane: BraceIconName = BraceIconName("paper-plane")
    public val Paperclip: BraceIconName = BraceIconName("paperclip")
    public val Paragraph: BraceIconName = BraceIconName("paragraph")
    public val Pause: BraceIconName = BraceIconName("pause")
    public val PenNib: BraceIconName = BraceIconName("pen-nib")
    public val PenNibPlus: BraceIconName = BraceIconName("pen-nib-plus")
    public val Pencil: BraceIconName = BraceIconName("pencil")
    public val Percent: BraceIconName = BraceIconName("percent")
    public val PersonBike: BraceIconName = BraceIconName("person-bike")
    public val PersonWalk: BraceIconName = BraceIconName("person-walk")
    public val Phone: BraceIconName = BraceIconName("phone")
    public val PhoneArrowRight: BraceIconName = BraceIconName("phone-arrow-right")
    public val PhoneMagnifyingGlass: BraceIconName = BraceIconName("phone-magnifying-glass")
    public val PhoneWaves: BraceIconName = BraceIconName("phone-waves")
    public val PiggyBank: BraceIconName = BraceIconName("piggy-bank")
    public val Pill: BraceIconName = BraceIconName("pill")
    public val Pistol: BraceIconName = BraceIconName("pistol")
    public val Play: BraceIconName = BraceIconName("play")
    public val Playbook: BraceIconName = BraceIconName("playbook")
    public val Plus: BraceIconName = BraceIconName("plus")
    public val PlusSmall: BraceIconName = BraceIconName("plus-small")
    public val PolygonArrowUpRight: BraceIconName = BraceIconName("polygon-arrow-up-right")
    public val PowerButton: BraceIconName = BraceIconName("power-button")
    public val Prescription: BraceIconName = BraceIconName("prescription")
    public val PrescriptionPlus: BraceIconName = BraceIconName("prescription-plus")
    public val Printer: BraceIconName = BraceIconName("printer")
    public val Pumpjack: BraceIconName = BraceIconName("pumpjack")
    public val PushPin: BraceIconName = BraceIconName("push-pin")
    public val PushPinSlash: BraceIconName = BraceIconName("push-pin-slash")
    public val Quotes: BraceIconName = BraceIconName("quotes")
    public val Rectangle: BraceIconName = BraceIconName("rectangle")
    public val RectangleDots: BraceIconName = BraceIconName("rectangle-dots")
    public val RectangleFooter: BraceIconName = BraceIconName("rectangle-footer")
    public val RectangleHeader: BraceIconName = BraceIconName("rectangle-header")
    public val RectangleHorizontalChevrons: BraceIconName = BraceIconName("rectangle-horizontal-chevrons")
    public val RectanglePlay: BraceIconName = BraceIconName("rectangle-play")
    public val RectanglePlusBottom: BraceIconName = BraceIconName("rectangle-plus-bottom")
    public val RectanglePlusTop: BraceIconName = BraceIconName("rectangle-plus-top")
    public val RectangleRotateLeft: BraceIconName = BraceIconName("rectangle-rotate-left")
    public val RectangleVerticalChevrons: BraceIconName = BraceIconName("rectangle-vertical-chevrons")
    public val RectanglesStack: BraceIconName = BraceIconName("rectangles-stack")
    public val Regex: BraceIconName = BraceIconName("regex")
    public val Resolve: BraceIconName = BraceIconName("resolve")
    public val RightJoin: BraceIconName = BraceIconName("right-join")
    public val Ring: BraceIconName = BraceIconName("ring")
    public val Rocket: BraceIconName = BraceIconName("rocket")
    public val RocketSlant: BraceIconName = BraceIconName("rocket-slant")
    public val Route: BraceIconName = BraceIconName("route")
    public val RowsPlusBottom: BraceIconName = BraceIconName("rows-plus-bottom")
    public val RowsPlusTop: BraceIconName = BraceIconName("rows-plus-top")
    public val RowsThree: BraceIconName = BraceIconName("rows-three")
    public val RowsTwo: BraceIconName = BraceIconName("rows-two")
    public val RowsXBottom: BraceIconName = BraceIconName("rows-x-bottom")
    public val RowsXTop: BraceIconName = BraceIconName("rows-x-top")
    public val Rss: BraceIconName = BraceIconName("rss")
    public val RssCheck: BraceIconName = BraceIconName("rss-check")
    public val Satellite: BraceIconName = BraceIconName("satellite")
    public val Scissors: BraceIconName = BraceIconName("scissors")
    public val SegmentedControl: BraceIconName = BraceIconName("segmented-control")
    public val Selection: BraceIconName = BraceIconName("selection")
    public val SelectionMinus: BraceIconName = BraceIconName("selection-minus")
    public val SelectionPen: BraceIconName = BraceIconName("selection-pen")
    public val SelectionPlus: BraceIconName = BraceIconName("selection-plus")
    public val Sensor: BraceIconName = BraceIconName("sensor")
    public val Server: BraceIconName = BraceIconName("server")
    public val ServerArrowDown: BraceIconName = BraceIconName("server-arrow-down")
    public val ServerCloud: BraceIconName = BraceIconName("server-cloud")
    public val Shapes: BraceIconName = BraceIconName("shapes")
    public val Shield: BraceIconName = BraceIconName("shield")
    public val ShieldBadge: BraceIconName = BraceIconName("shield-badge")
    public val ShieldPlus: BraceIconName = BraceIconName("shield-plus")
    public val Ship: BraceIconName = BraceIconName("ship")
    public val Shuriken: BraceIconName = BraceIconName("shuriken")
    public val SimCard: BraceIconName = BraceIconName("sim-card")
    public val SkipBackward: BraceIconName = BraceIconName("skip-backward")
    public val SkipForward: BraceIconName = BraceIconName("skip-forward")
    public val Slash: BraceIconName = BraceIconName("slash")
    public val Sliders: BraceIconName = BraceIconName("sliders")
    public val Snowflake: BraceIconName = BraceIconName("snowflake")
    public val SoccerBall: BraceIconName = BraceIconName("soccer-ball")
    public val Sparkles: BraceIconName = BraceIconName("sparkles")
    public val SpeakerHigh: BraceIconName = BraceIconName("speaker-high")
    public val SpeakerLow: BraceIconName = BraceIconName("speaker-low")
    public val SpeakerNone: BraceIconName = BraceIconName("speaker-none")
    public val Square: BraceIconName = BraceIconName("square")
    public val SquareArrowBottomOut: BraceIconName = BraceIconName("square-arrow-bottom-out")
    public val SquareArrowLeftIn: BraceIconName = BraceIconName("square-arrow-left-in")
    public val SquareArrowTopOut: BraceIconName = BraceIconName("square-arrow-top-out")
    public val SquareArrowUpRight: BraceIconName = BraceIconName("square-arrow-up-right")
    public val SquarePen: BraceIconName = BraceIconName("square-pen")
    public val SquarePlus: BraceIconName = BraceIconName("square-plus")
    public val SquareRotateLeft: BraceIconName = BraceIconName("square-rotate-left")
    public val SquareRotateRight: BraceIconName = BraceIconName("square-rotate-right")
    public val SquareSmall: BraceIconName = BraceIconName("square-small")
    public val SquareTPlus: BraceIconName = BraceIconName("square-t-plus")
    public val SquaresLinked: BraceIconName = BraceIconName("squares-linked")
    public val Stadium: BraceIconName = BraceIconName("stadium")
    public val Star: BraceIconName = BraceIconName("star")
    public val Stethoscope: BraceIconName = BraceIconName("stethoscope")
    public val Stop: BraceIconName = BraceIconName("stop")
    public val Stopwatch: BraceIconName = BraceIconName("stopwatch")
    public val Store: BraceIconName = BraceIconName("store")
    public val SubtractRightJoin: BraceIconName = BraceIconName("subtract-right-join")
    public val Sun: BraceIconName = BraceIconName("sun")
    public val Switch: BraceIconName = BraceIconName("switch")
    public val SymbolCircle: BraceIconName = BraceIconName("symbol-circle")
    public val SymbolCross: BraceIconName = BraceIconName("symbol-cross")
    public val SymbolDiamond: BraceIconName = BraceIconName("symbol-diamond")
    public val SymbolRectangle: BraceIconName = BraceIconName("symbol-rectangle")
    public val SymbolSquare: BraceIconName = BraceIconName("symbol-square")
    public val SymbolTriangleDown: BraceIconName = BraceIconName("symbol-triangle-down")
    public val SymbolTriangleUp: BraceIconName = BraceIconName("symbol-triangle-up")
    public val Syringe: BraceIconName = BraceIconName("syringe")
    public val Table: BraceIconName = BraceIconName("table")
    public val TableArrowRight: BraceIconName = BraceIconName("table-arrow-right")
    public val TableArrowsCw: BraceIconName = BraceIconName("table-arrows-cw")
    public val TableColumnPlus: BraceIconName = BraceIconName("table-column-plus")
    public val TableFunnel: BraceIconName = BraceIconName("table-funnel")
    public val TableHeader: BraceIconName = BraceIconName("table-header")
    public val TableHeaderPlus: BraceIconName = BraceIconName("table-header-plus")
    public val TableJoin: BraceIconName = BraceIconName("table-join")
    public val TablePanel: BraceIconName = BraceIconName("table-panel")
    public val TablePivot: BraceIconName = BraceIconName("table-pivot")
    public val TablePlus: BraceIconName = BraceIconName("table-plus")
    public val TableSlash: BraceIconName = BraceIconName("table-slash")
    public val Tag: BraceIconName = BraceIconName("tag")
    public val TagArrowsCw: BraceIconName = BraceIconName("tag-arrows-cw")
    public val TagDoubleChevronRight: BraceIconName = BraceIconName("tag-double-chevron-right")
    public val TagPlus: BraceIconName = BraceIconName("tag-plus")
    public val TagUndo: BraceIconName = BraceIconName("tag-undo")
    public val Tags: BraceIconName = BraceIconName("tags")
    public val Tank: BraceIconName = BraceIconName("tank")
    public val Taxi: BraceIconName = BraceIconName("taxi")
    public val Terminal: BraceIconName = BraceIconName("terminal")
    public val TerminalExclamation: BraceIconName = BraceIconName("terminal-exclamation")
    public val TextACheck: BraceIconName = BraceIconName("text-a-check")
    public val TextAlignCenter: BraceIconName = BraceIconName("text-align-center")
    public val TextAlignJustify: BraceIconName = BraceIconName("text-align-justify")
    public val TextAlignLeft: BraceIconName = BraceIconName("text-align-left")
    public val TextAlignRight: BraceIconName = BraceIconName("text-align-right")
    public val TextB: BraceIconName = BraceIconName("text-b")
    public val TextEndnote: BraceIconName = BraceIconName("text-endnote")
    public val TextH: BraceIconName = BraceIconName("text-h")
    public val TextHOne: BraceIconName = BraceIconName("text-h-one")
    public val TextHThree: BraceIconName = BraceIconName("text-h-three")
    public val TextHTwo: BraceIconName = BraceIconName("text-h-two")
    public val TextItalic: BraceIconName = BraceIconName("text-italic")
    public val TextLengthen: BraceIconName = BraceIconName("text-lengthen")
    public val TextResize: BraceIconName = BraceIconName("text-resize")
    public val TextShorten: BraceIconName = BraceIconName("text-shorten")
    public val TextStrikethrough: BraceIconName = BraceIconName("text-strikethrough")
    public val TextSubscript: BraceIconName = BraceIconName("text-subscript")
    public val TextSuperscript: BraceIconName = BraceIconName("text-superscript")
    public val TextUnderline: BraceIconName = BraceIconName("text-underline")
    public val TextWrapLines: BraceIconName = BraceIconName("text-wrap-lines")
    public val ThermometerHot: BraceIconName = BraceIconName("thermometer-hot")
    public val ThumbsDown: BraceIconName = BraceIconName("thumbs-down")
    public val ThumbsUp: BraceIconName = BraceIconName("thumbs-up")
    public val TilePlus: BraceIconName = BraceIconName("tile-plus")
    public val Tractor: BraceIconName = BraceIconName("tractor")
    public val Train: BraceIconName = BraceIconName("train")
    public val Translate: BraceIconName = BraceIconName("translate")
    public val Trash: BraceIconName = BraceIconName("trash")
    public val Tree: BraceIconName = BraceIconName("tree")
    public val TriangleExclamation: BraceIconName = BraceIconName("triangle-exclamation")
    public val Trophy: BraceIconName = BraceIconName("trophy")
    public val TruckFront: BraceIconName = BraceIconName("truck-front")
    public val Unresolve: BraceIconName = BraceIconName("unresolve")
    public val User: BraceIconName = BraceIconName("user")
    public val UserArrowLeft: BraceIconName = BraceIconName("user-arrow-left")
    public val UserArrowRight: BraceIconName = BraceIconName("user-arrow-right")
    public val UserBlocked: BraceIconName = BraceIconName("user-blocked")
    public val UserChat: BraceIconName = BraceIconName("user-chat")
    public val UserCircle: BraceIconName = BraceIconName("user-circle")
    public val UserPlus: BraceIconName = BraceIconName("user-plus")
    public val UserSquare: BraceIconName = BraceIconName("user-square")
    public val Users: BraceIconName = BraceIconName("users")
    public val UsersArrowRight: BraceIconName = BraceIconName("users-arrow-right")
    public val UsersThree: BraceIconName = BraceIconName("users-three")
    public val UtilityPole: BraceIconName = BraceIconName("utility-pole")
    public val Variable: BraceIconName = BraceIconName("variable")
    public val VariableLayers: BraceIconName = BraceIconName("variable-layers")
    public val Vector: BraceIconName = BraceIconName("vector")
    public val VideoCamera: BraceIconName = BraceIconName("video-camera")
    public val Virus: BraceIconName = BraceIconName("virus")
    public val Waveform: BraceIconName = BraceIconName("waveform")
    public val Waves: BraceIconName = BraceIconName("waves")
    public val Wind: BraceIconName = BraceIconName("wind")
    public val Window: BraceIconName = BraceIconName("window")
    public val WindowArrowUpLeft: BraceIconName = BraceIconName("window-arrow-up-left")
    public val WindowArrowUpLeftPlus: BraceIconName = BraceIconName("window-arrow-up-left-plus")
    public val WineGlass: BraceIconName = BraceIconName("wine-glass")
    public val Wrench: BraceIconName = BraceIconName("wrench")
    public val WrenchArrowRight: BraceIconName = BraceIconName("wrench-arrow-right")
    public val WrenchClock: BraceIconName = BraceIconName("wrench-clock")
    public val WrenchZ: BraceIconName = BraceIconName("wrench-z")
    public val X: BraceIconName = BraceIconName("x")
    public val XSmall: BraceIconName = BraceIconName("x-small")

    /** Canonical names in pinned manifest order. */
    public val all: List<BraceIconName> = listOf(
        Airplane,
        AlignBottom,
        AlignHorizontalCenter,
        AlignLeft,
        AlignRight,
        AlignTop,
        AlignVerticalCenter,
        Ammunition,
        Anchor,
        Antenna,
        Application,
        ApplicationArrowIn,
        ApplicationH,
        ApplicationPlus,
        Applications,
        Array,
        ArrayBoolean,
        ArrayDate,
        ArrayFloatingPoint,
        ArrayNumeric,
        ArrayObject,
        ArrayString,
        ArrayTimestamp,
        ArrowArcLeft,
        ArrowArcRight,
        ArrowBetweenBrackets,
        ArrowBetweenDots,
        ArrowCcw,
        ArrowCcwCheck,
        ArrowCcwClock,
        ArrowCcwExclamation,
        ArrowCcwPlayHistory,
        ArrowCircleDownRight,
        ArrowCw,
        ArrowDoubleFromDot,
        ArrowDown,
        ArrowDownAZ,
        ArrowDownFromLines,
        ArrowDownLeft,
        ArrowDownNineOne,
        ArrowDownOneNine,
        ArrowDownRight,
        ArrowDownToTray,
        ArrowDownZA,
        ArrowLeft,
        ArrowMerge,
        ArrowRight,
        ArrowRightFromArc,
        ArrowRightFromBracket,
        ArrowRightToArc,
        ArrowRightToBracket,
        ArrowSplit,
        ArrowThroughDot,
        ArrowToDot,
        ArrowTrendDown,
        ArrowTrendUp,
        ArrowTurnBottomLeft,
        ArrowTurnBottomRight,
        ArrowUp,
        ArrowUpFromLines,
        ArrowUpFromTray,
        ArrowUpLeft,
        ArrowUpRight,
        ArrowsBranchFromDot,
        ArrowsCcwCheck,
        ArrowsCw,
        ArrowsCwSlash,
        ArrowsDownUp,
        ArrowsHorizontal,
        ArrowsInDiagonal,
        ArrowsLeftRight,
        ArrowsMultiFromDot,
        ArrowsOutCardinal,
        ArrowsOutCorners,
        ArrowsOutDiagonal,
        ArrowsShuffle,
        ArrowsSpin,
        ArrowsUpArcRight,
        ArrowsUpDownLine,
        ArrowsVertical,
        Asterisk,
        At,
        Axle,
        BackwardTen,
        BadgeCheck,
        BarcodeRead,
        Barricade,
        BarsAscending,
        BarsDescending,
        BarsHorizontalAscending,
        BarsHorizontalDescending,
        Bell,
        BellCheck,
        BellPlus,
        BellZ,
        Binary,
        Blank,
        BlockDoubleChevronRight,
        Book,
        BookArrowUp,
        BookBookmark,
        BookOpen,
        Bookmark,
        Box,
        BoxArrowDown,
        BoxArrowUp,
        Brain,
        Briefcase,
        Broom,
        Bug,
        Buggy,
        Building,
        Bullseye,
        CabinetFiling,
        Calculator,
        Calendar,
        CalendarDots,
        Camera,
        Capsule,
        Car,
        CarCheck,
        CarQuestion,
        CaretDown,
        CaretLeft,
        CaretRight,
        CaretUp,
        CaretsHorizontal,
        CaretsVertical,
        CargoShip,
        Cart,
        CellTower,
        CellTowerMagnifyingGlass,
        ChartArea,
        ChartBar,
        ChartBarGrouped,
        ChartBarHorizontal,
        ChartCurvedRange,
        ChartDoughnut,
        ChartGantt,
        ChartLine,
        ChartLineArrowRight,
        ChartLineFunnel,
        ChartLineGear,
        ChartLineMagnifyingGlass,
        ChartLinePlus,
        ChartPie,
        ChartRegression,
        ChartScatter,
        ChartStackedBar,
        ChartStackedBarFull,
        ChartStep,
        ChartTrendUp,
        ChartWaterfall,
        ChatDots,
        ChatDotsPlus,
        ChatTeardropLightning,
        Chats,
        Check,
        CheckSmall,
        ChevronDown,
        ChevronLeft,
        ChevronLineLeft,
        ChevronLineRight,
        ChevronRight,
        ChevronUp,
        ChevronsHorizontalBetween,
        ChevronsIn,
        ChevronsOut,
        ChevronsVerticalBetween,
        Circle,
        CircleArrowDown,
        CircleArrowLeft,
        CircleArrowOut,
        CircleArrowRight,
        CircleArrowUp,
        CircleCheck,
        CircleCheckAlt,
        CircleCrosshairs,
        CircleCrosshairsDots,
        CircleDashed,
        CircleDashedRing,
        CircleDot,
        CircleDotPlus,
        CircleExclamation,
        CircleExclamationCheck,
        CircleExclamationPlus,
        CircleHalf,
        CircleInfo,
        CircleInfoSmall,
        CircleLightning,
        CircleMinus,
        CirclePlus,
        CirclePlusAlt,
        CircleQuestion,
        CircleRing,
        CircleSlash,
        CircleX,
        CircleXAlt,
        Clipboard,
        ClipboardFile,
        ClipboardVariable,
        Clock,
        ClockLocationPin,
        Cloud,
        CloudArrowDown,
        CloudArrowUp,
        CloudCheck,
        CloudRain,
        Code,
        CodeBlock,
        ColumnArrowLeft,
        ColumnArrowRight,
        ColumnCaretLeft,
        ColumnsLayout,
        ColumnsMerge,
        ColumnsMinusLeft,
        ColumnsPlusLeft,
        ColumnsPlusRight,
        ColumnsSplit,
        ColumnsThree,
        ColumnsTwo,
        ColumnsTwoCaretRight,
        ColumnsXLeft,
        ColumnsXRight,
        Comparison,
        Compass,
        Copy,
        CreditCard,
        Crop,
        Crown,
        CrystalBall,
        Cube,
        CubeCutout,
        CubeCutouts,
        CubeMinus,
        CubePen,
        CubePlus,
        Cubes,
        CurlyBraces,
        CurrencyDollar,
        CurrencyEuro,
        CurrencyPound,
        CurrencyWon,
        CurrencyYen,
        CursorSelection,
        CursorTextSelect,
        CurvedArea,
        Database,
        DatabaseArrowsCw,
        DatabaseCloud,
        DatabaseLightning,
        DatabaseMagnifyingGlass,
        DecimalNumber,
        Delta,
        DiagramLineage,
        DiagramTree,
        DigitsOneTwoThree,
        DistributeHorizontal,
        DistributeVertical,
        Divide,
        Dot,
        DotsArrowDownLine,
        DotsGridHorizontal,
        DotsGridVertical,
        DotsThree,
        DoubleChevronDown,
        DoubleChevronLeft,
        DoubleChevronRight,
        DoubleChevronUp,
        Drone,
        DroneUav,
        Droplet,
        Earth,
        EarthMagnifyingGlass,
        Easel,
        Eject,
        Envelope,
        Equals,
        Eraser,
        Excavator,
        Exclamation,
        Eye,
        EyeCheck,
        EyeSlash,
        FaceSmile,
        FastBackward,
        FastForward,
        FighterJet,
        File,
        FileArrowIn,
        FileArrowOut,
        FileCheck,
        FileCode,
        FileCss,
        FileLines,
        FileLock,
        FileRotateLeft,
        Film,
        Flag,
        Flame,
        Flashlight,
        Flask,
        FloppyDisk,
        Folder,
        FolderArrowIn,
        FolderArrowOut,
        FolderOpen,
        FolderOpenArrowOut,
        FolderPlus,
        FolderRoot,
        Font,
        ForwardTen,
        FrameCorners,
        FrameCube,
        FrameDot,
        FrameDotPlus,
        FrameDotX,
        FrameEye,
        FrameGroupObjects,
        FrameGroupObjectsX,
        FrameSquare,
        Function,
        FunctionArrowToColumn,
        FunctionArrowUp,
        FunctionMinimal,
        Funnel,
        FunnelArrowDown,
        FunnelArrowUp,
        FunnelCaretRight,
        FunnelCheck,
        FunnelList,
        FunnelUsers,
        FunnelX,
        GasCan,
        Gauge,
        Gavel,
        Gear,
        Gift,
        GitBranch,
        GitBranchLock,
        GitBranchLockOpen,
        GitBranchPlus,
        GitCommit,
        GitMerge,
        GitPull,
        GitRebase,
        Globe,
        GlobePlus,
        GlobeUsers,
        GraduationCap,
        GreaterThan,
        GreaterThanEqual,
        Grid,
        GridDiamond,
        GridHeatmap,
        GridLines,
        GridPlus,
        Hammer,
        Hand,
        HandPointDown,
        HandPointLeft,
        HandPointRight,
        HandPointUp,
        Hat,
        Headset,
        Heart,
        HeartCrack,
        Heatmap,
        Helicopter,
        HelperManagement,
        Hexagon,
        HighVoltageUtilityPole,
        Highlighter,
        House,
        Hurricane,
        IdCard,
        Image,
        ImageRotateLeft,
        ImageRotateRight,
        Inbox,
        InboxCircle,
        InboxFunnel,
        InboxGlobe,
        InboxMagnifyingGlass,
        InnerJoin,
        Intersection,
        IpAddress,
        Key,
        KeyBackspace,
        KeyCommand,
        KeyControl,
        KeyDelete,
        KeyEscape,
        KeyOption,
        KeyShift,
        KeyTab,
        Layer,
        LayerPlus,
        Layers,
        LayersPlus,
        LayoutBottomRowThreeTiles,
        LayoutBottomRowTwoTiles,
        LayoutLeftColumnThreeTiles,
        LayoutLeftColumnTwoTiles,
        LayoutRightColumnThreeTiles,
        LayoutRightColumnTwoTiles,
        LayoutTopRowThreeTiles,
        LayoutTopRowTwoTiles,
        LeftJoin,
        LessThan,
        LessThanEqual,
        LifeRing,
        Lightbulb,
        Lightning,
        LightningBolt,
        Link,
        LinkArrowIn,
        LinkSlash,
        List,
        ListBullets,
        ListBulletsDetail,
        ListCaretLeft,
        ListCaretRight,
        ListChecklist,
        ListColumns,
        ListFour,
        ListNumbers,
        ListPanel,
        ListPen,
        ListPlus,
        ListSort,
        ListSortAscending,
        ListSortDescending,
        ListX,
        Location,
        LocationPin,
        LocationPinPolygon,
        Lock,
        LockOpen,
        Locomotive,
        MagnifyingGlass,
        MagnifyingGlassLines,
        MagnifyingGlassMinus,
        MagnifyingGlassPlus,
        MagnifyingGlassT,
        ManyToMany,
        ManyToOne,
        Map,
        MapArrowIn,
        MapMagnifyingGlass,
        MapPlus,
        Markdown,
        Megaphone,
        Microphone,
        Minus,
        MinusSmall,
        MobilePhone,
        Monitor,
        Moon,
        Mountain,
        Music,
        NavigationArrow,
        NavigationArrowLeft,
        NavigationArrowRight,
        NetworkHub,
        NodesCircle,
        NodesCluster,
        NodesGrid,
        NodesGridGroup,
        NodesGridSkew,
        NodesHierarchy,
        NodesLinear,
        NodesNetwork,
        NodesNetworkAlt,
        NodesNetworkArrowIn,
        NodesNetworkCircle,
        NodesNetworkLightning,
        NodesPolygon,
        NodesSegment,
        NodesSquare,
        NotEqual,
        OilRig,
        OneToMany,
        OneToOne,
        OneToOneExchange,
        OneToOneMerge,
        OneToOnePlus,
        OuterJoin,
        Package,
        PackageArrowDown,
        PageBreak,
        PageLayout,
        PaintBucket,
        Paintbrush,
        PanelLayout,
        PanelList,
        PanelRight,
        PaperPlane,
        Paperclip,
        Paragraph,
        Pause,
        PenNib,
        PenNibPlus,
        Pencil,
        Percent,
        PersonBike,
        PersonWalk,
        Phone,
        PhoneArrowRight,
        PhoneMagnifyingGlass,
        PhoneWaves,
        PiggyBank,
        Pill,
        Pistol,
        Play,
        Playbook,
        Plus,
        PlusSmall,
        PolygonArrowUpRight,
        PowerButton,
        Prescription,
        PrescriptionPlus,
        Printer,
        Pumpjack,
        PushPin,
        PushPinSlash,
        Quotes,
        Rectangle,
        RectangleDots,
        RectangleFooter,
        RectangleHeader,
        RectangleHorizontalChevrons,
        RectanglePlay,
        RectanglePlusBottom,
        RectanglePlusTop,
        RectangleRotateLeft,
        RectangleVerticalChevrons,
        RectanglesStack,
        Regex,
        Resolve,
        RightJoin,
        Ring,
        Rocket,
        RocketSlant,
        Route,
        RowsPlusBottom,
        RowsPlusTop,
        RowsThree,
        RowsTwo,
        RowsXBottom,
        RowsXTop,
        Rss,
        RssCheck,
        Satellite,
        Scissors,
        SegmentedControl,
        Selection,
        SelectionMinus,
        SelectionPen,
        SelectionPlus,
        Sensor,
        Server,
        ServerArrowDown,
        ServerCloud,
        Shapes,
        Shield,
        ShieldBadge,
        ShieldPlus,
        Ship,
        Shuriken,
        SimCard,
        SkipBackward,
        SkipForward,
        Slash,
        Sliders,
        Snowflake,
        SoccerBall,
        Sparkles,
        SpeakerHigh,
        SpeakerLow,
        SpeakerNone,
        Square,
        SquareArrowBottomOut,
        SquareArrowLeftIn,
        SquareArrowTopOut,
        SquareArrowUpRight,
        SquarePen,
        SquarePlus,
        SquareRotateLeft,
        SquareRotateRight,
        SquareSmall,
        SquareTPlus,
        SquaresLinked,
        Stadium,
        Star,
        Stethoscope,
        Stop,
        Stopwatch,
        Store,
        SubtractRightJoin,
        Sun,
        Switch,
        SymbolCircle,
        SymbolCross,
        SymbolDiamond,
        SymbolRectangle,
        SymbolSquare,
        SymbolTriangleDown,
        SymbolTriangleUp,
        Syringe,
        Table,
        TableArrowRight,
        TableArrowsCw,
        TableColumnPlus,
        TableFunnel,
        TableHeader,
        TableHeaderPlus,
        TableJoin,
        TablePanel,
        TablePivot,
        TablePlus,
        TableSlash,
        Tag,
        TagArrowsCw,
        TagDoubleChevronRight,
        TagPlus,
        TagUndo,
        Tags,
        Tank,
        Taxi,
        Terminal,
        TerminalExclamation,
        TextACheck,
        TextAlignCenter,
        TextAlignJustify,
        TextAlignLeft,
        TextAlignRight,
        TextB,
        TextEndnote,
        TextH,
        TextHOne,
        TextHThree,
        TextHTwo,
        TextItalic,
        TextLengthen,
        TextResize,
        TextShorten,
        TextStrikethrough,
        TextSubscript,
        TextSuperscript,
        TextUnderline,
        TextWrapLines,
        ThermometerHot,
        ThumbsDown,
        ThumbsUp,
        TilePlus,
        Tractor,
        Train,
        Translate,
        Trash,
        Tree,
        TriangleExclamation,
        Trophy,
        TruckFront,
        Unresolve,
        User,
        UserArrowLeft,
        UserArrowRight,
        UserBlocked,
        UserChat,
        UserCircle,
        UserPlus,
        UserSquare,
        Users,
        UsersArrowRight,
        UsersThree,
        UtilityPole,
        Variable,
        VariableLayers,
        Vector,
        VideoCamera,
        Virus,
        Waveform,
        Waves,
        Wind,
        Window,
        WindowArrowUpLeft,
        WindowArrowUpLeftPlus,
        WineGlass,
        Wrench,
        WrenchArrowRight,
        WrenchClock,
        WrenchZ,
        X,
        XSmall,
    )
}
