// Generated by scripts/generate_blueprint_icons.py from the pinned Blueprint icon manifest. DO NOT EDIT.
package io.github.joelromanpr.brace.blueprinticons

import io.github.joelromanpr.brace.icons.BraceIconName

/** Typed names for all 706 pinned Blueprint glyphs. Artwork lives in the opt-in AAR. */
public object BraceBlueprintIconNames {
    public val Blank: BraceIconName = BraceIconName("blank")
    public val Style: BraceIconName = BraceIconName("style")
    public val AlignLeft: BraceIconName = BraceIconName("align-left")
    public val AlignCenter: BraceIconName = BraceIconName("align-center")
    public val AlignRight: BraceIconName = BraceIconName("align-right")
    public val AlignJustify: BraceIconName = BraceIconName("align-justify")
    public val Bold: BraceIconName = BraceIconName("bold")
    public val Italic: BraceIconName = BraceIconName("italic")
    public val Underline: BraceIconName = BraceIconName("underline")
    public val SearchAround: BraceIconName = BraceIconName("search-around")
    public val GraphRemove: BraceIconName = BraceIconName("graph-remove")
    public val GroupObjects: BraceIconName = BraceIconName("group-objects")
    public val MergeLinks: BraceIconName = BraceIconName("merge-links")
    public val Layout: BraceIconName = BraceIconName("layout")
    public val LayoutAuto: BraceIconName = BraceIconName("layout-auto")
    public val LayoutCircle: BraceIconName = BraceIconName("layout-circle")
    public val LayoutHierarchy: BraceIconName = BraceIconName("layout-hierarchy")
    public val LayoutGrid: BraceIconName = BraceIconName("layout-grid")
    public val LayoutGroupBy: BraceIconName = BraceIconName("layout-group-by")
    public val LayoutSkewGrid: BraceIconName = BraceIconName("layout-skew-grid")
    public val Geosearch: BraceIconName = BraceIconName("geosearch")
    public val Heatmap: BraceIconName = BraceIconName("heatmap")
    public val DriveTime: BraceIconName = BraceIconName("drive-time")
    public val Select: BraceIconName = BraceIconName("select")
    public val PredictiveAnalysis: BraceIconName = BraceIconName("predictive-analysis")
    public val Layers: BraceIconName = BraceIconName("layers")
    public val Locate: BraceIconName = BraceIconName("locate")
    public val Bookmark: BraceIconName = BraceIconName("bookmark")
    public val Citation: BraceIconName = BraceIconName("citation")
    public val Tag: BraceIconName = BraceIconName("tag")
    public val Clipboard: BraceIconName = BraceIconName("clipboard")
    public val Selection: BraceIconName = BraceIconName("selection")
    public val TimelineEvents: BraceIconName = BraceIconName("timeline-events")
    public val TimelineLineChart: BraceIconName = BraceIconName("timeline-line-chart")
    public val TimelineBarChart: BraceIconName = BraceIconName("timeline-bar-chart")
    public val Applications: BraceIconName = BraceIconName("applications")
    public val Projects: BraceIconName = BraceIconName("projects")
    public val Changes: BraceIconName = BraceIconName("changes")
    public val Notifications: BraceIconName = BraceIconName("notifications")
    public val Lock: BraceIconName = BraceIconName("lock")
    public val Unlock: BraceIconName = BraceIconName("unlock")
    public val User: BraceIconName = BraceIconName("user")
    public val SearchTemplate: BraceIconName = BraceIconName("search-template")
    public val Inbox: BraceIconName = BraceIconName("inbox")
    public val More: BraceIconName = BraceIconName("more")
    public val Help: BraceIconName = BraceIconName("help")
    public val Calendar: BraceIconName = BraceIconName("calendar")
    public val Media: BraceIconName = BraceIconName("media")
    public val Link: BraceIconName = BraceIconName("link")
    public val Share: BraceIconName = BraceIconName("share")
    public val Download: BraceIconName = BraceIconName("download")
    public val Document: BraceIconName = BraceIconName("document")
    public val Properties: BraceIconName = BraceIconName("properties")
    public val Import: BraceIconName = BraceIconName("import")
    public val Export: BraceIconName = BraceIconName("export")
    public val Minimize: BraceIconName = BraceIconName("minimize")
    public val Maximize: BraceIconName = BraceIconName("maximize")
    public val Tick: BraceIconName = BraceIconName("tick")
    public val Cross: BraceIconName = BraceIconName("cross")
    public val Plus: BraceIconName = BraceIconName("plus")
    public val Minus: BraceIconName = BraceIconName("minus")
    public val ArrowLeft: BraceIconName = BraceIconName("arrow-left")
    public val ArrowRight: BraceIconName = BraceIconName("arrow-right")
    public val Exchange: BraceIconName = BraceIconName("exchange")
    public val Comparison: BraceIconName = BraceIconName("comparison")
    public val List: BraceIconName = BraceIconName("list")
    public val Filter: BraceIconName = BraceIconName("filter")
    public val Confirm: BraceIconName = BraceIconName("confirm")
    public val Fork: BraceIconName = BraceIconName("fork")
    public val Trash: BraceIconName = BraceIconName("trash")
    public val Person: BraceIconName = BraceIconName("person")
    public val People: BraceIconName = BraceIconName("people")
    public val Add: BraceIconName = BraceIconName("add")
    public val Remove: BraceIconName = BraceIconName("remove")
    public val Geolocation: BraceIconName = BraceIconName("geolocation")
    public val ZoomIn: BraceIconName = BraceIconName("zoom-in")
    public val ZoomOut: BraceIconName = BraceIconName("zoom-out")
    public val Refresh: BraceIconName = BraceIconName("refresh")
    public val Delete: BraceIconName = BraceIconName("delete")
    public val Cog: BraceIconName = BraceIconName("cog")
    public val Flag: BraceIconName = BraceIconName("flag")
    public val Pin: BraceIconName = BraceIconName("pin")
    public val WarningSign: BraceIconName = BraceIconName("warning-sign")
    public val Error: BraceIconName = BraceIconName("error")
    public val InfoSign: BraceIconName = BraceIconName("info-sign")
    public val CreditCard: BraceIconName = BraceIconName("credit-card")
    public val Edit: BraceIconName = BraceIconName("edit")
    public val History: BraceIconName = BraceIconName("history")
    public val Search: BraceIconName = BraceIconName("search")
    public val LogOut: BraceIconName = BraceIconName("log-out")
    public val Star: BraceIconName = BraceIconName("star")
    public val StarEmpty: BraceIconName = BraceIconName("star-empty")
    public val SortAlphabetical: BraceIconName = BraceIconName("sort-alphabetical")
    public val SortNumerical: BraceIconName = BraceIconName("sort-numerical")
    public val Sort: BraceIconName = BraceIconName("sort")
    public val FolderOpen: BraceIconName = BraceIconName("folder-open")
    public val FolderClose: BraceIconName = BraceIconName("folder-close")
    public val FolderShared: BraceIconName = BraceIconName("folder-shared")
    public val CaretUp: BraceIconName = BraceIconName("caret-up")
    public val CaretRight: BraceIconName = BraceIconName("caret-right")
    public val CaretDown: BraceIconName = BraceIconName("caret-down")
    public val CaretLeft: BraceIconName = BraceIconName("caret-left")
    public val MenuOpen: BraceIconName = BraceIconName("menu-open")
    public val MenuClosed: BraceIconName = BraceIconName("menu-closed")
    public val Feed: BraceIconName = BraceIconName("feed")
    public val TwoColumns: BraceIconName = BraceIconName("two-columns")
    public val OneColumn: BraceIconName = BraceIconName("one-column")
    public val Dot: BraceIconName = BraceIconName("dot")
    public val Property: BraceIconName = BraceIconName("property")
    public val Time: BraceIconName = BraceIconName("time")
    public val Disable: BraceIconName = BraceIconName("disable")
    public val Unpin: BraceIconName = BraceIconName("unpin")
    public val Flows: BraceIconName = BraceIconName("flows")
    public val NewTextBox: BraceIconName = BraceIconName("new-text-box")
    public val NewLink: BraceIconName = BraceIconName("new-link")
    public val NewObject: BraceIconName = BraceIconName("new-object")
    public val PathSearch: BraceIconName = BraceIconName("path-search")
    public val AutomaticUpdates: BraceIconName = BraceIconName("automatic-updates")
    public val PageLayout: BraceIconName = BraceIconName("page-layout")
    public val Code: BraceIconName = BraceIconName("code")
    public val Map: BraceIconName = BraceIconName("map")
    public val SearchText: BraceIconName = BraceIconName("search-text")
    public val Envelope: BraceIconName = BraceIconName("envelope")
    public val Paperclip: BraceIconName = BraceIconName("paperclip")
    public val Label: BraceIconName = BraceIconName("label")
    public val Globe: BraceIconName = BraceIconName("globe")
    public val Home: BraceIconName = BraceIconName("home")
    public val Th: BraceIconName = BraceIconName("th")
    public val ThList: BraceIconName = BraceIconName("th-list")
    public val ThDerived: BraceIconName = BraceIconName("th-derived")
    public val Circle: BraceIconName = BraceIconName("circle")
    public val Draw: BraceIconName = BraceIconName("draw")
    public val Insert: BraceIconName = BraceIconName("insert")
    public val HelperManagement: BraceIconName = BraceIconName("helper-management")
    public val SendTo: BraceIconName = BraceIconName("send-to")
    public val EyeOpen: BraceIconName = BraceIconName("eye-open")
    public val FolderSharedOpen: BraceIconName = BraceIconName("folder-shared-open")
    public val SocialMedia: BraceIconName = BraceIconName("social-media")
    public val ArrowUp: BraceIconName = BraceIconName("arrow-up")
    public val ArrowDown: BraceIconName = BraceIconName("arrow-down")
    public val ArrowsHorizontal: BraceIconName = BraceIconName("arrows-horizontal")
    public val ArrowsVertical: BraceIconName = BraceIconName("arrows-vertical")
    public val Resolve: BraceIconName = BraceIconName("resolve")
    public val Graph: BraceIconName = BraceIconName("graph")
    public val Briefcase: BraceIconName = BraceIconName("briefcase")
    public val Dollar: BraceIconName = BraceIconName("dollar")
    public val Ninja: BraceIconName = BraceIconName("ninja")
    public val Delta: BraceIconName = BraceIconName("delta")
    public val Barcode: BraceIconName = BraceIconName("barcode")
    public val Torch: BraceIconName = BraceIconName("torch")
    public val Widget: BraceIconName = BraceIconName("widget")
    public val Unresolve: BraceIconName = BraceIconName("unresolve")
    public val Offline: BraceIconName = BraceIconName("offline")
    public val ZoomToFit: BraceIconName = BraceIconName("zoom-to-fit")
    public val AddToArtifact: BraceIconName = BraceIconName("add-to-artifact")
    public val MapMarker: BraceIconName = BraceIconName("map-marker")
    public val Chart: BraceIconName = BraceIconName("chart")
    public val Control: BraceIconName = BraceIconName("control")
    public val MultiSelect: BraceIconName = BraceIconName("multi-select")
    public val DirectionLeft: BraceIconName = BraceIconName("direction-left")
    public val DirectionRight: BraceIconName = BraceIconName("direction-right")
    public val Database: BraceIconName = BraceIconName("database")
    public val PieChart: BraceIconName = BraceIconName("pie-chart")
    public val FullCircle: BraceIconName = BraceIconName("full-circle")
    public val Square: BraceIconName = BraceIconName("square")
    public val Print: BraceIconName = BraceIconName("print")
    public val Presentation: BraceIconName = BraceIconName("presentation")
    public val UngroupObjects: BraceIconName = BraceIconName("ungroup-objects")
    public val Chat: BraceIconName = BraceIconName("chat")
    public val Comment: BraceIconName = BraceIconName("comment")
    public val CircleArrowRight: BraceIconName = BraceIconName("circle-arrow-right")
    public val CircleArrowLeft: BraceIconName = BraceIconName("circle-arrow-left")
    public val CircleArrowUp: BraceIconName = BraceIconName("circle-arrow-up")
    public val CircleArrowDown: BraceIconName = BraceIconName("circle-arrow-down")
    public val Upload: BraceIconName = BraceIconName("upload")
    public val Asterisk: BraceIconName = BraceIconName("asterisk")
    public val Cloud: BraceIconName = BraceIconName("cloud")
    public val CloudDownload: BraceIconName = BraceIconName("cloud-download")
    public val CloudUpload: BraceIconName = BraceIconName("cloud-upload")
    public val Repeat: BraceIconName = BraceIconName("repeat")
    public val Move: BraceIconName = BraceIconName("move")
    public val ChevronLeft: BraceIconName = BraceIconName("chevron-left")
    public val ChevronRight: BraceIconName = BraceIconName("chevron-right")
    public val ChevronUp: BraceIconName = BraceIconName("chevron-up")
    public val ChevronDown: BraceIconName = BraceIconName("chevron-down")
    public val Random: BraceIconName = BraceIconName("random")
    public val Fullscreen: BraceIconName = BraceIconName("fullscreen")
    public val LogIn: BraceIconName = BraceIconName("log-in")
    public val Heart: BraceIconName = BraceIconName("heart")
    public val Office: BraceIconName = BraceIconName("office")
    public val Duplicate: BraceIconName = BraceIconName("duplicate")
    public val BanCircle: BraceIconName = BraceIconName("ban-circle")
    public val Camera: BraceIconName = BraceIconName("camera")
    public val MobileVideo: BraceIconName = BraceIconName("mobile-video")
    public val Video: BraceIconName = BraceIconName("video")
    public val Film: BraceIconName = BraceIconName("film")
    public val Settings: BraceIconName = BraceIconName("settings")
    public val VolumeOff: BraceIconName = BraceIconName("volume-off")
    public val VolumeDown: BraceIconName = BraceIconName("volume-down")
    public val VolumeUp: BraceIconName = BraceIconName("volume-up")
    public val Music: BraceIconName = BraceIconName("music")
    public val StepBackward: BraceIconName = BraceIconName("step-backward")
    public val FastBackward: BraceIconName = BraceIconName("fast-backward")
    public val Pause: BraceIconName = BraceIconName("pause")
    public val Stop: BraceIconName = BraceIconName("stop")
    public val Play: BraceIconName = BraceIconName("play")
    public val FastForward: BraceIconName = BraceIconName("fast-forward")
    public val StepForward: BraceIconName = BraceIconName("step-forward")
    public val Eject: BraceIconName = BraceIconName("eject")
    public val Record: BraceIconName = BraceIconName("record")
    public val Desktop: BraceIconName = BraceIconName("desktop")
    public val Phone: BraceIconName = BraceIconName("phone")
    public val Lightbulb: BraceIconName = BraceIconName("lightbulb")
    public val Glass: BraceIconName = BraceIconName("glass")
    public val Tint: BraceIconName = BraceIconName("tint")
    public val Flash: BraceIconName = BraceIconName("flash")
    public val Font: BraceIconName = BraceIconName("font")
    public val Header: BraceIconName = BraceIconName("header")
    public val Saved: BraceIconName = BraceIconName("saved")
    public val FloppyDisk: BraceIconName = BraceIconName("floppy-disk")
    public val Book: BraceIconName = BraceIconName("book")
    public val HandRight: BraceIconName = BraceIconName("hand-right")
    public val HandUp: BraceIconName = BraceIconName("hand-up")
    public val HandDown: BraceIconName = BraceIconName("hand-down")
    public val HandLeft: BraceIconName = BraceIconName("hand-left")
    public val ThumbsUp: BraceIconName = BraceIconName("thumbs-up")
    public val ThumbsDown: BraceIconName = BraceIconName("thumbs-down")
    public val Box: BraceIconName = BraceIconName("box")
    public val Compressed: BraceIconName = BraceIconName("compressed")
    public val ShoppingCart: BraceIconName = BraceIconName("shopping-cart")
    public val Shop: BraceIconName = BraceIconName("shop")
    public val LayoutLinear: BraceIconName = BraceIconName("layout-linear")
    public val Undo: BraceIconName = BraceIconName("undo")
    public val Redo: BraceIconName = BraceIconName("redo")
    public val CodeBlock: BraceIconName = BraceIconName("code-block")
    public val DoubleCaretVertical: BraceIconName = BraceIconName("double-caret-vertical")
    public val DoubleCaretHorizontal: BraceIconName = BraceIconName("double-caret-horizontal")
    public val SortAlphabeticalDesc: BraceIconName = BraceIconName("sort-alphabetical-desc")
    public val SortNumericalDesc: BraceIconName = BraceIconName("sort-numerical-desc")
    public val TakeAction: BraceIconName = BraceIconName("take-action")
    public val Contrast: BraceIconName = BraceIconName("contrast")
    public val EyeOff: BraceIconName = BraceIconName("eye-off")
    public val TimelineAreaChart: BraceIconName = BraceIconName("timeline-area-chart")
    public val DoughnutChart: BraceIconName = BraceIconName("doughnut-chart")
    public val Layer: BraceIconName = BraceIconName("layer")
    public val Grid: BraceIconName = BraceIconName("grid")
    public val PolygonFilter: BraceIconName = BraceIconName("polygon-filter")
    public val AddToFolder: BraceIconName = BraceIconName("add-to-folder")
    public val LayoutBalloon: BraceIconName = BraceIconName("layout-balloon")
    public val LayoutSortedClusters: BraceIconName = BraceIconName("layout-sorted-clusters")
    public val SortAsc: BraceIconName = BraceIconName("sort-asc")
    public val SortDesc: BraceIconName = BraceIconName("sort-desc")
    public val SmallCross: BraceIconName = BraceIconName("small-cross")
    public val SmallTick: BraceIconName = BraceIconName("small-tick")
    public val Power: BraceIconName = BraceIconName("power")
    public val ColumnLayout: BraceIconName = BraceIconName("column-layout")
    public val ArrowTopLeft: BraceIconName = BraceIconName("arrow-top-left")
    public val ArrowTopRight: BraceIconName = BraceIconName("arrow-top-right")
    public val ArrowBottomRight: BraceIconName = BraceIconName("arrow-bottom-right")
    public val ArrowBottomLeft: BraceIconName = BraceIconName("arrow-bottom-left")
    public val Mugshot: BraceIconName = BraceIconName("mugshot")
    public val Headset: BraceIconName = BraceIconName("headset")
    public val TextHighlight: BraceIconName = BraceIconName("text-highlight")
    public val Hand: BraceIconName = BraceIconName("hand")
    public val ChevronBackward: BraceIconName = BraceIconName("chevron-backward")
    public val ChevronForward: BraceIconName = BraceIconName("chevron-forward")
    public val RotateDocument: BraceIconName = BraceIconName("rotate-document")
    public val RotatePage: BraceIconName = BraceIconName("rotate-page")
    public val Badge: BraceIconName = BraceIconName("badge")
    public val GridView: BraceIconName = BraceIconName("grid-view")
    public val Function: BraceIconName = BraceIconName("function")
    public val WaterfallChart: BraceIconName = BraceIconName("waterfall-chart")
    public val StackedChart: BraceIconName = BraceIconName("stacked-chart")
    public val Pulse: BraceIconName = BraceIconName("pulse")
    public val NewPerson: BraceIconName = BraceIconName("new-person")
    public val ExcludeRow: BraceIconName = BraceIconName("exclude-row")
    public val PivotTable: BraceIconName = BraceIconName("pivot-table")
    public val SegmentedControl: BraceIconName = BraceIconName("segmented-control")
    public val Highlight: BraceIconName = BraceIconName("highlight")
    public val FilterList: BraceIconName = BraceIconName("filter-list")
    public val Cut: BraceIconName = BraceIconName("cut")
    public val Annotation: BraceIconName = BraceIconName("annotation")
    public val Pivot: BraceIconName = BraceIconName("pivot")
    public val Ring: BraceIconName = BraceIconName("ring")
    public val HeatGrid: BraceIconName = BraceIconName("heat-grid")
    public val GanttChart: BraceIconName = BraceIconName("gantt-chart")
    public val Variable: BraceIconName = BraceIconName("variable")
    public val Manual: BraceIconName = BraceIconName("manual")
    public val AddRowTop: BraceIconName = BraceIconName("add-row-top")
    public val AddRowBottom: BraceIconName = BraceIconName("add-row-bottom")
    public val AddColumnLeft: BraceIconName = BraceIconName("add-column-left")
    public val AddColumnRight: BraceIconName = BraceIconName("add-column-right")
    public val RemoveRowTop: BraceIconName = BraceIconName("remove-row-top")
    public val RemoveRowBottom: BraceIconName = BraceIconName("remove-row-bottom")
    public val RemoveColumnLeft: BraceIconName = BraceIconName("remove-column-left")
    public val RemoveColumnRight: BraceIconName = BraceIconName("remove-column-right")
    public val DoubleChevronLeft: BraceIconName = BraceIconName("double-chevron-left")
    public val DoubleChevronRight: BraceIconName = BraceIconName("double-chevron-right")
    public val DoubleChevronUp: BraceIconName = BraceIconName("double-chevron-up")
    public val DoubleChevronDown: BraceIconName = BraceIconName("double-chevron-down")
    public val KeyControl: BraceIconName = BraceIconName("key-control")
    public val KeyCommand: BraceIconName = BraceIconName("key-command")
    public val KeyShift: BraceIconName = BraceIconName("key-shift")
    public val KeyBackspace: BraceIconName = BraceIconName("key-backspace")
    public val KeyDelete: BraceIconName = BraceIconName("key-delete")
    public val KeyEscape: BraceIconName = BraceIconName("key-escape")
    public val KeyEnter: BraceIconName = BraceIconName("key-enter")
    public val Calculator: BraceIconName = BraceIconName("calculator")
    public val HorizontalBarChart: BraceIconName = BraceIconName("horizontal-bar-chart")
    public val SmallPlus: BraceIconName = BraceIconName("small-plus")
    public val SmallMinus: BraceIconName = BraceIconName("small-minus")
    public val StepChart: BraceIconName = BraceIconName("step-chart")
    public val Euro: BraceIconName = BraceIconName("euro")
    public val DragHandleVertical: BraceIconName = BraceIconName("drag-handle-vertical")
    public val DragHandleHorizontal: BraceIconName = BraceIconName("drag-handle-horizontal")
    public val MobilePhone: BraceIconName = BraceIconName("mobile-phone")
    public val SimCard: BraceIconName = BraceIconName("sim-card")
    public val TrendingUp: BraceIconName = BraceIconName("trending-up")
    public val TrendingDown: BraceIconName = BraceIconName("trending-down")
    public val CurvedRangeChart: BraceIconName = BraceIconName("curved-range-chart")
    public val VerticalBarChartDesc: BraceIconName = BraceIconName("vertical-bar-chart-desc")
    public val HorizontalBarChartDesc: BraceIconName = BraceIconName("horizontal-bar-chart-desc")
    public val DocumentOpen: BraceIconName = BraceIconName("document-open")
    public val DocumentShare: BraceIconName = BraceIconName("document-share")
    public val HorizontalDistribution: BraceIconName = BraceIconName("horizontal-distribution")
    public val VerticalDistribution: BraceIconName = BraceIconName("vertical-distribution")
    public val AlignmentLeft: BraceIconName = BraceIconName("alignment-left")
    public val AlignmentVerticalCenter: BraceIconName = BraceIconName("alignment-vertical-center")
    public val AlignmentRight: BraceIconName = BraceIconName("alignment-right")
    public val AlignmentTop: BraceIconName = BraceIconName("alignment-top")
    public val AlignmentHorizontalCenter: BraceIconName = BraceIconName("alignment-horizontal-center")
    public val AlignmentBottom: BraceIconName = BraceIconName("alignment-bottom")
    public val GitPull: BraceIconName = BraceIconName("git-pull")
    public val GitMerge: BraceIconName = BraceIconName("git-merge")
    public val GitBranch: BraceIconName = BraceIconName("git-branch")
    public val GitCommit: BraceIconName = BraceIconName("git-commit")
    public val GitPush: BraceIconName = BraceIconName("git-push")
    public val Build: BraceIconName = BraceIconName("build")
    public val SymbolCircle: BraceIconName = BraceIconName("symbol-circle")
    public val SymbolSquare: BraceIconName = BraceIconName("symbol-square")
    public val SymbolDiamond: BraceIconName = BraceIconName("symbol-diamond")
    public val SymbolCross: BraceIconName = BraceIconName("symbol-cross")
    public val SymbolTriangleUp: BraceIconName = BraceIconName("symbol-triangle-up")
    public val SymbolTriangleDown: BraceIconName = BraceIconName("symbol-triangle-down")
    public val Wrench: BraceIconName = BraceIconName("wrench")
    public val Application: BraceIconName = BraceIconName("application")
    public val SendToGraph: BraceIconName = BraceIconName("send-to-graph")
    public val SendToMap: BraceIconName = BraceIconName("send-to-map")
    public val JoinTable: BraceIconName = BraceIconName("join-table")
    public val DeriveColumn: BraceIconName = BraceIconName("derive-column")
    public val ImageRotateLeft: BraceIconName = BraceIconName("image-rotate-left")
    public val ImageRotateRight: BraceIconName = BraceIconName("image-rotate-right")
    public val KnownVehicle: BraceIconName = BraceIconName("known-vehicle")
    public val UnknownVehicle: BraceIconName = BraceIconName("unknown-vehicle")
    public val ScatterPlot: BraceIconName = BraceIconName("scatter-plot")
    public val OilField: BraceIconName = BraceIconName("oil-field")
    public val Rig: BraceIconName = BraceIconName("rig")
    public val MapCreate: BraceIconName = BraceIconName("map-create")
    public val KeyOption: BraceIconName = BraceIconName("key-option")
    public val ListDetailView: BraceIconName = BraceIconName("list-detail-view")
    public val SwapVertical: BraceIconName = BraceIconName("swap-vertical")
    public val SwapHorizontal: BraceIconName = BraceIconName("swap-horizontal")
    public val NumberedList: BraceIconName = BraceIconName("numbered-list")
    public val NewGridItem: BraceIconName = BraceIconName("new-grid-item")
    public val GitRepo: BraceIconName = BraceIconName("git-repo")
    public val GitNewBranch: BraceIconName = BraceIconName("git-new-branch")
    public val ManuallyEnteredData: BraceIconName = BraceIconName("manually-entered-data")
    public val Airplane: BraceIconName = BraceIconName("airplane")
    public val MergeColumns: BraceIconName = BraceIconName("merge-columns")
    public val SplitColumns: BraceIconName = BraceIconName("split-columns")
    public val Dashboard: BraceIconName = BraceIconName("dashboard")
    public val PublishFunction: BraceIconName = BraceIconName("publish-function")
    public val Path: BraceIconName = BraceIconName("path")
    public val Moon: BraceIconName = BraceIconName("moon")
    public val RemoveColumn: BraceIconName = BraceIconName("remove-column")
    public val Numerical: BraceIconName = BraceIconName("numerical")
    public val KeyTab: BraceIconName = BraceIconName("key-tab")
    public val RegressionChart: BraceIconName = BraceIconName("regression-chart")
    public val Translate: BraceIconName = BraceIconName("translate")
    public val EyeOn: BraceIconName = BraceIconName("eye-on")
    public val VerticalBarChartAsc: BraceIconName = BraceIconName("vertical-bar-chart-asc")
    public val HorizontalBarChartAsc: BraceIconName = BraceIconName("horizontal-bar-chart-asc")
    public val GroupedBarChart: BraceIconName = BraceIconName("grouped-bar-chart")
    public val FullStackedChart: BraceIconName = BraceIconName("full-stacked-chart")
    public val Endorsed: BraceIconName = BraceIconName("endorsed")
    public val Follower: BraceIconName = BraceIconName("follower")
    public val Following: BraceIconName = BraceIconName("following")
    public val Menu: BraceIconName = BraceIconName("menu")
    public val CollapseAll: BraceIconName = BraceIconName("collapse-all")
    public val ExpandAll: BraceIconName = BraceIconName("expand-all")
    public val Intersection: BraceIconName = BraceIconName("intersection")
    public val BlockedPerson: BraceIconName = BraceIconName("blocked-person")
    public val Slash: BraceIconName = BraceIconName("slash")
    public val Percentage: BraceIconName = BraceIconName("percentage")
    public val Satellite: BraceIconName = BraceIconName("satellite")
    public val Paragraph: BraceIconName = BraceIconName("paragraph")
    public val BankAccount: BraceIconName = BraceIconName("bank-account")
    public val CellTower: BraceIconName = BraceIconName("cell-tower")
    public val IdNumber: BraceIconName = BraceIconName("id-number")
    public val IpAddress: BraceIconName = BraceIconName("ip-address")
    public val Eraser: BraceIconName = BraceIconName("eraser")
    public val Issue: BraceIconName = BraceIconName("issue")
    public val IssueNew: BraceIconName = BraceIconName("issue-new")
    public val IssueClosed: BraceIconName = BraceIconName("issue-closed")
    public val PanelStats: BraceIconName = BraceIconName("panel-stats")
    public val PanelTable: BraceIconName = BraceIconName("panel-table")
    public val TickCircle: BraceIconName = BraceIconName("tick-circle")
    public val Prescription: BraceIconName = BraceIconName("prescription")
    public val NewPrescription: BraceIconName = BraceIconName("new-prescription")
    public val FilterKeep: BraceIconName = BraceIconName("filter-keep")
    public val FilterRemove: BraceIconName = BraceIconName("filter-remove")
    public val Key: BraceIconName = BraceIconName("key")
    public val FeedSubscribed: BraceIconName = BraceIconName("feed-subscribed")
    public val WidgetButton: BraceIconName = BraceIconName("widget-button")
    public val WidgetHeader: BraceIconName = BraceIconName("widget-header")
    public val WidgetFooter: BraceIconName = BraceIconName("widget-footer")
    public val HeaderOne: BraceIconName = BraceIconName("header-one")
    public val HeaderTwo: BraceIconName = BraceIconName("header-two")
    public val Form: BraceIconName = BraceIconName("form")
    public val SeriesAdd: BraceIconName = BraceIconName("series-add")
    public val SeriesSearch: BraceIconName = BraceIconName("series-search")
    public val SeriesFiltered: BraceIconName = BraceIconName("series-filtered")
    public val SeriesDerived: BraceIconName = BraceIconName("series-derived")
    public val SeriesConfiguration: BraceIconName = BraceIconName("series-configuration")
    public val Console: BraceIconName = BraceIconName("console")
    public val Compass: BraceIconName = BraceIconName("compass")
    public val Walk: BraceIconName = BraceIconName("walk")
    public val Taxi: BraceIconName = BraceIconName("taxi")
    public val Train: BraceIconName = BraceIconName("train")
    public val HeartBroken: BraceIconName = BraceIconName("heart-broken")
    public val InnerJoin: BraceIconName = BraceIconName("inner-join")
    public val LeftJoin: BraceIconName = BraceIconName("left-join")
    public val RightJoin: BraceIconName = BraceIconName("right-join")
    public val Strikethrough: BraceIconName = BraceIconName("strikethrough")
    public val Updated: BraceIconName = BraceIconName("updated")
    public val Outdated: BraceIconName = BraceIconName("outdated")
    public val Flame: BraceIconName = BraceIconName("flame")
    public val FolderNew: BraceIconName = BraceIconName("folder-new")
    public val Mountain: BraceIconName = BraceIconName("mountain")
    public val Shield: BraceIconName = BraceIconName("shield")
    public val DiagramTree: BraceIconName = BraceIconName("diagram-tree")
    public val Crown: BraceIconName = BraceIconName("crown")
    public val GlobeNetwork: BraceIconName = BraceIconName("globe-network")
    public val Snowflake: BraceIconName = BraceIconName("snowflake")
    public val Tree: BraceIconName = BraceIconName("tree")
    public val NotificationsUpdated: BraceIconName = BraceIconName("notifications-updated")
    public val ListColumns: BraceIconName = BraceIconName("list-columns")
    public val FlowLinear: BraceIconName = BraceIconName("flow-linear")
    public val FlowBranch: BraceIconName = BraceIconName("flow-branch")
    public val FlowReview: BraceIconName = BraceIconName("flow-review")
    public val FlowReviewBranch: BraceIconName = BraceIconName("flow-review-branch")
    public val FlowEnd: BraceIconName = BraceIconName("flow-end")
    public val Clean: BraceIconName = BraceIconName("clean")
    public val ThFiltered: BraceIconName = BraceIconName("th-filtered")
    public val Lifesaver: BraceIconName = BraceIconName("lifesaver")
    public val Cube: BraceIconName = BraceIconName("cube")
    public val CubeAdd: BraceIconName = BraceIconName("cube-add")
    public val CubeRemove: BraceIconName = BraceIconName("cube-remove")
    public val InboxFiltered: BraceIconName = BraceIconName("inbox-filtered")
    public val InboxGeo: BraceIconName = BraceIconName("inbox-geo")
    public val InboxSearch: BraceIconName = BraceIconName("inbox-search")
    public val InboxUpdate: BraceIconName = BraceIconName("inbox-update")
    public val Inheritance: BraceIconName = BraceIconName("inheritance")
    public val Reset: BraceIconName = BraceIconName("reset")
    public val FilterOpen: BraceIconName = BraceIconName("filter-open")
    public val ThDisconnect: BraceIconName = BraceIconName("th-disconnect")
    public val Equals: BraceIconName = BraceIconName("equals")
    public val NotEqualTo: BraceIconName = BraceIconName("not-equal-to")
    public val GreaterThan: BraceIconName = BraceIconName("greater-than")
    public val GreaterThanOrEqualTo: BraceIconName = BraceIconName("greater-than-or-equal-to")
    public val LessThan: BraceIconName = BraceIconName("less-than")
    public val LessThanOrEqualTo: BraceIconName = BraceIconName("less-than-or-equal-to")
    public val Learning: BraceIconName = BraceIconName("learning")
    public val NewLayer: BraceIconName = BraceIconName("new-layer")
    public val NewLayers: BraceIconName = BraceIconName("new-layers")
    public val Stopwatch: BraceIconName = BraceIconName("stopwatch")
    public val Archive: BraceIconName = BraceIconName("archive")
    public val Unarchive: BraceIconName = BraceIconName("unarchive")
    public val DataLineage: BraceIconName = BraceIconName("data-lineage")
    public val NewDrawing: BraceIconName = BraceIconName("new-drawing")
    public val SignalSearch: BraceIconName = BraceIconName("signal-search")
    public val BringData: BraceIconName = BraceIconName("bring-data")
    public val Tractor: BraceIconName = BraceIconName("tractor")
    public val Truck: BraceIconName = BraceIconName("truck")
    public val Diagnosis: BraceIconName = BraceIconName("diagnosis")
    public val LabTest: BraceIconName = BraceIconName("lab-test")
    public val Virus: BraceIconName = BraceIconName("virus")
    public val InheritedGroup: BraceIconName = BraceIconName("inherited-group")
    public val Hat: BraceIconName = BraceIconName("hat")
    public val Cycle: BraceIconName = BraceIconName("cycle")
    public val Route: BraceIconName = BraceIconName("route")
    public val Modal: BraceIconName = BraceIconName("modal")
    public val ModalFilled: BraceIconName = BraceIconName("modal-filled")
    public val DrawerLeft: BraceIconName = BraceIconName("drawer-left")
    public val DrawerLeftFilled: BraceIconName = BraceIconName("drawer-left-filled")
    public val DrawerRight: BraceIconName = BraceIconName("drawer-right")
    public val DrawerRightFilled: BraceIconName = BraceIconName("drawer-right-filled")
    public val AppHeader: BraceIconName = BraceIconName("app-header")
    public val SendMessage: BraceIconName = BraceIconName("send-message")
    public val Backlink: BraceIconName = BraceIconName("backlink")
    public val Geofence: BraceIconName = BraceIconName("geofence")
    public val DataConnection: BraceIconName = BraceIconName("data-connection")
    public val Switch: BraceIconName = BraceIconName("switch")
    public val Array: BraceIconName = BraceIconName("array")
    public val ArrayBoolean: BraceIconName = BraceIconName("array-boolean")
    public val ArrayDate: BraceIconName = BraceIconName("array-date")
    public val ArrayNumeric: BraceIconName = BraceIconName("array-numeric")
    public val ArrayString: BraceIconName = BraceIconName("array-string")
    public val ArrayTimestamp: BraceIconName = BraceIconName("array-timestamp")
    public val LayerOutline: BraceIconName = BraceIconName("layer-outline")
    public val NotificationsSnooze: BraceIconName = BraceIconName("notifications-snooze")
    public val HighPriority: BraceIconName = BraceIconName("high-priority")
    public val Emoji: BraceIconName = BraceIconName("emoji")
    public val AddLocation: BraceIconName = BraceIconName("add-location")
    public val Shapes: BraceIconName = BraceIconName("shapes")
    public val SharedFilter: BraceIconName = BraceIconName("shared-filter")
    public val OneToOne: BraceIconName = BraceIconName("one-to-one")
    public val OneToMany: BraceIconName = BraceIconName("one-to-many")
    public val ManyToOne: BraceIconName = BraceIconName("many-to-one")
    public val ManyToMany: BraceIconName = BraceIconName("many-to-many")
    public val StadiumGeometry: BraceIconName = BraceIconName("stadium-geometry")
    public val AreaOfInterest: BraceIconName = BraceIconName("area-of-interest")
    public val Buggy: BraceIconName = BraceIconName("buggy")
    public val Antenna: BraceIconName = BraceIconName("antenna")
    public val Tank: BraceIconName = BraceIconName("tank")
    public val ThirdParty: BraceIconName = BraceIconName("third-party")
    public val Rocket: BraceIconName = BraceIconName("rocket")
    public val RocketSlant: BraceIconName = BraceIconName("rocket-slant")
    public val HeaderThree: BraceIconName = BraceIconName("header-three")
    public val Helicopter: BraceIconName = BraceIconName("helicopter")
    public val Syringe: BraceIconName = BraceIconName("syringe")
    public val Temperature: BraceIconName = BraceIconName("temperature")
    public val Waves: BraceIconName = BraceIconName("waves")
    public val Rain: BraceIconName = BraceIconName("rain")
    public val Lightning: BraceIconName = BraceIconName("lightning")
    public val Wind: BraceIconName = BraceIconName("wind")
    public val Hurricane: BraceIconName = BraceIconName("hurricane")
    public val Nest: BraceIconName = BraceIconName("nest")
    public val Target: BraceIconName = BraceIconName("target")
    public val SmallSquare: BraceIconName = BraceIconName("small-square")
    public val Ship: BraceIconName = BraceIconName("ship")
    public val CargoShip: BraceIconName = BraceIconName("cargo-ship")
    public val Clip: BraceIconName = BraceIconName("clip")
    public val AddClip: BraceIconName = BraceIconName("add-clip")
    public val Rectangle: BraceIconName = BraceIconName("rectangle")
    public val SymbolRectangle: BraceIconName = BraceIconName("symbol-rectangle")
    public val Fuel: BraceIconName = BraceIconName("fuel")
    public val Playbook: BraceIconName = BraceIconName("playbook")
    public val RectHeight: BraceIconName = BraceIconName("rect-height")
    public val RectWidth: BraceIconName = BraceIconName("rect-width")
    public val Divide: BraceIconName = BraceIconName("divide")
    public val ColorFill: BraceIconName = BraceIconName("color-fill")
    public val HorizontalInbetween: BraceIconName = BraceIconName("horizontal-inbetween")
    public val VerticalInbetween: BraceIconName = BraceIconName("vertical-inbetween")
    public val OpenApplication: BraceIconName = BraceIconName("open-application")
    public val FloatingPoint: BraceIconName = BraceIconName("floating-point")
    public val ArrayFloatingPoint: BraceIconName = BraceIconName("array-floating-point")
    public val Bug: BraceIconName = BraceIconName("bug")
    public val Regex: BraceIconName = BraceIconName("regex")
    public val Anchor: BraceIconName = BraceIconName("anchor")
    public val At: BraceIconName = BraceIconName("at")
    public val LowVoltagePole: BraceIconName = BraceIconName("low-voltage-pole")
    public val HighVoltagePole: BraceIconName = BraceIconName("high-voltage-pole")
    public val SmallInfoSign: BraceIconName = BraceIconName("small-info-sign")
    public val AimpointsTarget: BraceIconName = BraceIconName("aimpoints-target")
    public val CrossCircle: BraceIconName = BraceIconName("cross-circle")
    public val Intelligence: BraceIconName = BraceIconName("intelligence")
    public val Axle: BraceIconName = BraceIconName("axle")
    public val Subscript: BraceIconName = BraceIconName("subscript")
    public val Superscript: BraceIconName = BraceIconName("superscript")
    public val Locomotive: BraceIconName = BraceIconName("locomotive")
    public val Sensor: BraceIconName = BraceIconName("sensor")
    public val Model: BraceIconName = BraceIconName("model")
    public val LengthenText: BraceIconName = BraceIconName("lengthen-text")
    public val ShortenText: BraceIconName = BraceIconName("shorten-text")
    public val SpellCheck: BraceIconName = BraceIconName("spell-check")
    public val Detection: BraceIconName = BraceIconName("detection")
    public val Ammunition: BraceIconName = BraceIconName("ammunition")
    public val Microphone: BraceIconName = BraceIconName("microphone")
    public val Geotime: BraceIconName = BraceIconName("geotime")
    public val Unlink: BraceIconName = BraceIconName("unlink")
    public val PasteVariable: BraceIconName = BraceIconName("paste-variable")
    public val PhoneCall: BraceIconName = BraceIconName("phone-call")
    public val PhoneForward: BraceIconName = BraceIconName("phone-forward")
    public val NewShield: BraceIconName = BraceIconName("new-shield")
    public val GroupItem: BraceIconName = BraceIconName("group-item")
    public val Input: BraceIconName = BraceIconName("input")
    public val Generate: BraceIconName = BraceIconName("generate")
    public val Explain: BraceIconName = BraceIconName("explain")
    public val CloudTick: BraceIconName = BraceIconName("cloud-tick")
    public val Trophy: BraceIconName = BraceIconName("trophy")
    public val SoccerBall: BraceIconName = BraceIconName("soccer-ball")
    public val SportsStadium: BraceIconName = BraceIconName("sports-stadium")
    public val Team: BraceIconName = BraceIconName("team")
    public val Crop: BraceIconName = BraceIconName("crop")
    public val BringForward: BraceIconName = BraceIconName("bring-forward")
    public val SendBackward: BraceIconName = BraceIconName("send-backward")
    public val Endnote: BraceIconName = BraceIconName("endnote")
    public val BinaryNumber: BraceIconName = BraceIconName("binary-number")
    public val CurlyBraces: BraceIconName = BraceIconName("curly-braces")
    public val Bullseye: BraceIconName = BraceIconName("bullseye")
    public val CloudServer: BraceIconName = BraceIconName("cloud-server")
    public val ClipboardFile: BraceIconName = BraceIconName("clipboard-file")
    public val BackwardTen: BraceIconName = BraceIconName("backward-ten")
    public val ForwardTen: BraceIconName = BraceIconName("forward-ten")
    public val Vector: BraceIconName = BraceIconName("vector")
    public val LayoutTwoColumns: BraceIconName = BraceIconName("layout-two-columns")
    public val LayoutTwoRows: BraceIconName = BraceIconName("layout-two-rows")
    public val LayoutThreeColumns: BraceIconName = BraceIconName("layout-three-columns")
    public val LayoutThreeRows: BraceIconName = BraceIconName("layout-three-rows")
    public val LayoutBottomRowTwoTiles: BraceIconName = BraceIconName("layout-bottom-row-two-tiles")
    public val LayoutBottomRowThreeTiles: BraceIconName = BraceIconName("layout-bottom-row-three-tiles")
    public val LayoutLeftColumnTwoTiles: BraceIconName = BraceIconName("layout-left-column-two-tiles")
    public val LayoutLeftColumnThreeTiles: BraceIconName = BraceIconName("layout-left-column-three-tiles")
    public val LayoutRightColumnTwoTiles: BraceIconName = BraceIconName("layout-right-column-two-tiles")
    public val LayoutRightColumnThreeTiles: BraceIconName = BraceIconName("layout-right-column-three-tiles")
    public val LayoutTopRowTwoTiles: BraceIconName = BraceIconName("layout-top-row-two-tiles")
    public val LayoutTopRowThreeTiles: BraceIconName = BraceIconName("layout-top-row-three-tiles")
    public val CssStyle: BraceIconName = BraceIconName("css-style")
    public val DataSync: BraceIconName = BraceIconName("data-sync")
    public val Excavator: BraceIconName = BraceIconName("excavator")
    public val TableSync: BraceIconName = BraceIconName("table-sync")
    public val DataSearch: BraceIconName = BraceIconName("data-search")
    public val Output: BraceIconName = BraceIconName("output")
    public val RangeRing: BraceIconName = BraceIconName("range-ring")
    public val BlockPromote: BraceIconName = BraceIconName("block-promote")
    public val Cubes: BraceIconName = BraceIconName("cubes")
    public val Hexagon: BraceIconName = BraceIconName("hexagon")
    public val Package: BraceIconName = BraceIconName("package")
    public val Pill: BraceIconName = BraceIconName("pill")
    public val ServerInstall: BraceIconName = BraceIconName("server-install")
    public val Server: BraceIconName = BraceIconName("server")
    public val TagAdd: BraceIconName = BraceIconName("tag-add")
    public val TagPromote: BraceIconName = BraceIconName("tag-promote")
    public val TagRefresh: BraceIconName = BraceIconName("tag-refresh")
    public val TagUndo: BraceIconName = BraceIconName("tag-undo")
    public val Tags: BraceIconName = BraceIconName("tags")
    public val WrenchRedo: BraceIconName = BraceIconName("wrench-redo")
    public val WrenchSnooze: BraceIconName = BraceIconName("wrench-snooze")
    public val WrenchTime: BraceIconName = BraceIconName("wrench-time")
    public val Panel: BraceIconName = BraceIconName("panel")
    public val GlobeNetworkAdd: BraceIconName = BraceIconName("globe-network-add")
    public val CubeEdit: BraceIconName = BraceIconName("cube-edit")
    public val FighterJet: BraceIconName = BraceIconName("fighter-jet")
    public val LinkedSquares: BraceIconName = BraceIconName("linked-squares")
    public val BritishPound: BraceIconName = BraceIconName("british-pound")
    public val ArrowsArc: BraceIconName = BraceIconName("arrows-arc")
    public val RotateCw: BraceIconName = BraceIconName("rotate-cw")
    public val RotateCcw: BraceIconName = BraceIconName("rotate-ccw")
    public val ThAdd: BraceIconName = BraceIconName("th-add")
    public val ThListAdd: BraceIconName = BraceIconName("th-list-add")
    public val ThVirtual: BraceIconName = BraceIconName("th-virtual")
    public val ThVirtualAdd: BraceIconName = BraceIconName("th-virtual-add")
    public val FilterSortAsc: BraceIconName = BraceIconName("filter-sort-asc")
    public val FilterSortDesc: BraceIconName = BraceIconName("filter-sort-desc")
    public val ObjectView: BraceIconName = BraceIconName("object-view")
    public val DataCloud: BraceIconName = BraceIconName("data-cloud")
    public val SubtractRightJoin: BraceIconName = BraceIconName("subtract-right-join")
    public val RunHistory: BraceIconName = BraceIconName("run-history")
    public val ArrayObject: BraceIconName = BraceIconName("array-object")
    public val Construction: BraceIconName = BraceIconName("construction")
    public val Announcement: BraceIconName = BraceIconName("announcement")
    public val PhoneSearch: BraceIconName = BraceIconName("phone-search")
    public val NotificationsAdd: BraceIconName = BraceIconName("notifications-add")
    public val SelectionBox: BraceIconName = BraceIconName("selection-box")
    public val SelectionBoxAdd: BraceIconName = BraceIconName("selection-box-add")
    public val SelectionBoxEdit: BraceIconName = BraceIconName("selection-box-edit")
    public val Pistol: BraceIconName = BraceIconName("pistol")
    public val AddChild: BraceIconName = BraceIconName("add-child")
    public val AddParent: BraceIconName = BraceIconName("add-parent")
    public val RootFolder: BraceIconName = BraceIconName("root-folder")
    public val DocumentCode: BraceIconName = BraceIconName("document-code")
    public val DocumentLocked: BraceIconName = BraceIconName("document-locked")
    public val GiftBox: BraceIconName = BraceIconName("gift-box")
    public val DeleteClip: BraceIconName = BraceIconName("delete-clip")
    public val Sweep: BraceIconName = BraceIconName("sweep")
    public val PageBreak: BraceIconName = BraceIconName("page-break")
    public val BranchLocked: BraceIconName = BraceIconName("branch-locked")
    public val BranchUnlocked: BraceIconName = BraceIconName("branch-unlocked")
    public val SelectionBoxRemove: BraceIconName = BraceIconName("selection-box-remove")
    public val Markdown: BraceIconName = BraceIconName("markdown")
    public val RefreshOff: BraceIconName = BraceIconName("refresh-off")
    public val VariableLayer: BraceIconName = BraceIconName("variable-layer")
    public val GitRebase: BraceIconName = BraceIconName("git-rebase")
    public val ConsoleAlert: BraceIconName = BraceIconName("console-alert")
    public val WrapLines: BraceIconName = BraceIconName("wrap-lines")
    public val Won: BraceIconName = BraceIconName("won")
    public val Yen: BraceIconName = BraceIconName("yen")
    public val Drone: BraceIconName = BraceIconName("drone")
    public val DroneUav: BraceIconName = BraceIconName("drone-uav")
    public val Spin: BraceIconName = BraceIconName("spin")
    public val FunctionMinimal: BraceIconName = BraceIconName("function-minimal")
    public val CubeCutout: BraceIconName = BraceIconName("cube-cutout")
    public val CubeCutouts: BraceIconName = BraceIconName("cube-cutouts")
    public val ForkEnd: BraceIconName = BraceIconName("fork-end")
    public val AddApplication: BraceIconName = BraceIconName("add-application")
    public val AddDerivedColumn: BraceIconName = BraceIconName("add-derived-column")
    public val AddTile: BraceIconName = BraceIconName("add-tile")
    public val CircleDashed: BraceIconName = BraceIconName("circle-dashed")
    public val Descendant: BraceIconName = BraceIconName("descendant")
    public val Engagement: BraceIconName = BraceIconName("engagement")
    public val NewComment: BraceIconName = BraceIconName("new-comment")
    public val OuterJoin: BraceIconName = BraceIconName("outer-join")
    public val Popout: BraceIconName = BraceIconName("popout")
    public val FrameToFrame: BraceIconName = BraceIconName("frame-to-frame")
    public val CrystalBall: BraceIconName = BraceIconName("crystal-ball")

    /** All pinned names in Blueprint metadata order. */
    public val all: List<BraceIconName> = listOf(
        Blank,
        Style,
        AlignLeft,
        AlignCenter,
        AlignRight,
        AlignJustify,
        Bold,
        Italic,
        Underline,
        SearchAround,
        GraphRemove,
        GroupObjects,
        MergeLinks,
        Layout,
        LayoutAuto,
        LayoutCircle,
        LayoutHierarchy,
        LayoutGrid,
        LayoutGroupBy,
        LayoutSkewGrid,
        Geosearch,
        Heatmap,
        DriveTime,
        Select,
        PredictiveAnalysis,
        Layers,
        Locate,
        Bookmark,
        Citation,
        Tag,
        Clipboard,
        Selection,
        TimelineEvents,
        TimelineLineChart,
        TimelineBarChart,
        Applications,
        Projects,
        Changes,
        Notifications,
        Lock,
        Unlock,
        User,
        SearchTemplate,
        Inbox,
        More,
        Help,
        Calendar,
        Media,
        Link,
        Share,
        Download,
        Document,
        Properties,
        Import,
        Export,
        Minimize,
        Maximize,
        Tick,
        Cross,
        Plus,
        Minus,
        ArrowLeft,
        ArrowRight,
        Exchange,
        Comparison,
        List,
        Filter,
        Confirm,
        Fork,
        Trash,
        Person,
        People,
        Add,
        Remove,
        Geolocation,
        ZoomIn,
        ZoomOut,
        Refresh,
        Delete,
        Cog,
        Flag,
        Pin,
        WarningSign,
        Error,
        InfoSign,
        CreditCard,
        Edit,
        History,
        Search,
        LogOut,
        Star,
        StarEmpty,
        SortAlphabetical,
        SortNumerical,
        Sort,
        FolderOpen,
        FolderClose,
        FolderShared,
        CaretUp,
        CaretRight,
        CaretDown,
        CaretLeft,
        MenuOpen,
        MenuClosed,
        Feed,
        TwoColumns,
        OneColumn,
        Dot,
        Property,
        Time,
        Disable,
        Unpin,
        Flows,
        NewTextBox,
        NewLink,
        NewObject,
        PathSearch,
        AutomaticUpdates,
        PageLayout,
        Code,
        Map,
        SearchText,
        Envelope,
        Paperclip,
        Label,
        Globe,
        Home,
        Th,
        ThList,
        ThDerived,
        Circle,
        Draw,
        Insert,
        HelperManagement,
        SendTo,
        EyeOpen,
        FolderSharedOpen,
        SocialMedia,
        ArrowUp,
        ArrowDown,
        ArrowsHorizontal,
        ArrowsVertical,
        Resolve,
        Graph,
        Briefcase,
        Dollar,
        Ninja,
        Delta,
        Barcode,
        Torch,
        Widget,
        Unresolve,
        Offline,
        ZoomToFit,
        AddToArtifact,
        MapMarker,
        Chart,
        Control,
        MultiSelect,
        DirectionLeft,
        DirectionRight,
        Database,
        PieChart,
        FullCircle,
        Square,
        Print,
        Presentation,
        UngroupObjects,
        Chat,
        Comment,
        CircleArrowRight,
        CircleArrowLeft,
        CircleArrowUp,
        CircleArrowDown,
        Upload,
        Asterisk,
        Cloud,
        CloudDownload,
        CloudUpload,
        Repeat,
        Move,
        ChevronLeft,
        ChevronRight,
        ChevronUp,
        ChevronDown,
        Random,
        Fullscreen,
        LogIn,
        Heart,
        Office,
        Duplicate,
        BanCircle,
        Camera,
        MobileVideo,
        Video,
        Film,
        Settings,
        VolumeOff,
        VolumeDown,
        VolumeUp,
        Music,
        StepBackward,
        FastBackward,
        Pause,
        Stop,
        Play,
        FastForward,
        StepForward,
        Eject,
        Record,
        Desktop,
        Phone,
        Lightbulb,
        Glass,
        Tint,
        Flash,
        Font,
        Header,
        Saved,
        FloppyDisk,
        Book,
        HandRight,
        HandUp,
        HandDown,
        HandLeft,
        ThumbsUp,
        ThumbsDown,
        Box,
        Compressed,
        ShoppingCart,
        Shop,
        LayoutLinear,
        Undo,
        Redo,
        CodeBlock,
        DoubleCaretVertical,
        DoubleCaretHorizontal,
        SortAlphabeticalDesc,
        SortNumericalDesc,
        TakeAction,
        Contrast,
        EyeOff,
        TimelineAreaChart,
        DoughnutChart,
        Layer,
        Grid,
        PolygonFilter,
        AddToFolder,
        LayoutBalloon,
        LayoutSortedClusters,
        SortAsc,
        SortDesc,
        SmallCross,
        SmallTick,
        Power,
        ColumnLayout,
        ArrowTopLeft,
        ArrowTopRight,
        ArrowBottomRight,
        ArrowBottomLeft,
        Mugshot,
        Headset,
        TextHighlight,
        Hand,
        ChevronBackward,
        ChevronForward,
        RotateDocument,
        RotatePage,
        Badge,
        GridView,
        Function,
        WaterfallChart,
        StackedChart,
        Pulse,
        NewPerson,
        ExcludeRow,
        PivotTable,
        SegmentedControl,
        Highlight,
        FilterList,
        Cut,
        Annotation,
        Pivot,
        Ring,
        HeatGrid,
        GanttChart,
        Variable,
        Manual,
        AddRowTop,
        AddRowBottom,
        AddColumnLeft,
        AddColumnRight,
        RemoveRowTop,
        RemoveRowBottom,
        RemoveColumnLeft,
        RemoveColumnRight,
        DoubleChevronLeft,
        DoubleChevronRight,
        DoubleChevronUp,
        DoubleChevronDown,
        KeyControl,
        KeyCommand,
        KeyShift,
        KeyBackspace,
        KeyDelete,
        KeyEscape,
        KeyEnter,
        Calculator,
        HorizontalBarChart,
        SmallPlus,
        SmallMinus,
        StepChart,
        Euro,
        DragHandleVertical,
        DragHandleHorizontal,
        MobilePhone,
        SimCard,
        TrendingUp,
        TrendingDown,
        CurvedRangeChart,
        VerticalBarChartDesc,
        HorizontalBarChartDesc,
        DocumentOpen,
        DocumentShare,
        HorizontalDistribution,
        VerticalDistribution,
        AlignmentLeft,
        AlignmentVerticalCenter,
        AlignmentRight,
        AlignmentTop,
        AlignmentHorizontalCenter,
        AlignmentBottom,
        GitPull,
        GitMerge,
        GitBranch,
        GitCommit,
        GitPush,
        Build,
        SymbolCircle,
        SymbolSquare,
        SymbolDiamond,
        SymbolCross,
        SymbolTriangleUp,
        SymbolTriangleDown,
        Wrench,
        Application,
        SendToGraph,
        SendToMap,
        JoinTable,
        DeriveColumn,
        ImageRotateLeft,
        ImageRotateRight,
        KnownVehicle,
        UnknownVehicle,
        ScatterPlot,
        OilField,
        Rig,
        MapCreate,
        KeyOption,
        ListDetailView,
        SwapVertical,
        SwapHorizontal,
        NumberedList,
        NewGridItem,
        GitRepo,
        GitNewBranch,
        ManuallyEnteredData,
        Airplane,
        MergeColumns,
        SplitColumns,
        Dashboard,
        PublishFunction,
        Path,
        Moon,
        RemoveColumn,
        Numerical,
        KeyTab,
        RegressionChart,
        Translate,
        EyeOn,
        VerticalBarChartAsc,
        HorizontalBarChartAsc,
        GroupedBarChart,
        FullStackedChart,
        Endorsed,
        Follower,
        Following,
        Menu,
        CollapseAll,
        ExpandAll,
        Intersection,
        BlockedPerson,
        Slash,
        Percentage,
        Satellite,
        Paragraph,
        BankAccount,
        CellTower,
        IdNumber,
        IpAddress,
        Eraser,
        Issue,
        IssueNew,
        IssueClosed,
        PanelStats,
        PanelTable,
        TickCircle,
        Prescription,
        NewPrescription,
        FilterKeep,
        FilterRemove,
        Key,
        FeedSubscribed,
        WidgetButton,
        WidgetHeader,
        WidgetFooter,
        HeaderOne,
        HeaderTwo,
        Form,
        SeriesAdd,
        SeriesSearch,
        SeriesFiltered,
        SeriesDerived,
        SeriesConfiguration,
        Console,
        Compass,
        Walk,
        Taxi,
        Train,
        HeartBroken,
        InnerJoin,
        LeftJoin,
        RightJoin,
        Strikethrough,
        Updated,
        Outdated,
        Flame,
        FolderNew,
        Mountain,
        Shield,
        DiagramTree,
        Crown,
        GlobeNetwork,
        Snowflake,
        Tree,
        NotificationsUpdated,
        ListColumns,
        FlowLinear,
        FlowBranch,
        FlowReview,
        FlowReviewBranch,
        FlowEnd,
        Clean,
        ThFiltered,
        Lifesaver,
        Cube,
        CubeAdd,
        CubeRemove,
        InboxFiltered,
        InboxGeo,
        InboxSearch,
        InboxUpdate,
        Inheritance,
        Reset,
        FilterOpen,
        ThDisconnect,
        Equals,
        NotEqualTo,
        GreaterThan,
        GreaterThanOrEqualTo,
        LessThan,
        LessThanOrEqualTo,
        Learning,
        NewLayer,
        NewLayers,
        Stopwatch,
        Archive,
        Unarchive,
        DataLineage,
        NewDrawing,
        SignalSearch,
        BringData,
        Tractor,
        Truck,
        Diagnosis,
        LabTest,
        Virus,
        InheritedGroup,
        Hat,
        Cycle,
        Route,
        Modal,
        ModalFilled,
        DrawerLeft,
        DrawerLeftFilled,
        DrawerRight,
        DrawerRightFilled,
        AppHeader,
        SendMessage,
        Backlink,
        Geofence,
        DataConnection,
        Switch,
        Array,
        ArrayBoolean,
        ArrayDate,
        ArrayNumeric,
        ArrayString,
        ArrayTimestamp,
        LayerOutline,
        NotificationsSnooze,
        HighPriority,
        Emoji,
        AddLocation,
        Shapes,
        SharedFilter,
        OneToOne,
        OneToMany,
        ManyToOne,
        ManyToMany,
        StadiumGeometry,
        AreaOfInterest,
        Buggy,
        Antenna,
        Tank,
        ThirdParty,
        Rocket,
        RocketSlant,
        HeaderThree,
        Helicopter,
        Syringe,
        Temperature,
        Waves,
        Rain,
        Lightning,
        Wind,
        Hurricane,
        Nest,
        Target,
        SmallSquare,
        Ship,
        CargoShip,
        Clip,
        AddClip,
        Rectangle,
        SymbolRectangle,
        Fuel,
        Playbook,
        RectHeight,
        RectWidth,
        Divide,
        ColorFill,
        HorizontalInbetween,
        VerticalInbetween,
        OpenApplication,
        FloatingPoint,
        ArrayFloatingPoint,
        Bug,
        Regex,
        Anchor,
        At,
        LowVoltagePole,
        HighVoltagePole,
        SmallInfoSign,
        AimpointsTarget,
        CrossCircle,
        Intelligence,
        Axle,
        Subscript,
        Superscript,
        Locomotive,
        Sensor,
        Model,
        LengthenText,
        ShortenText,
        SpellCheck,
        Detection,
        Ammunition,
        Microphone,
        Geotime,
        Unlink,
        PasteVariable,
        PhoneCall,
        PhoneForward,
        NewShield,
        GroupItem,
        Input,
        Generate,
        Explain,
        CloudTick,
        Trophy,
        SoccerBall,
        SportsStadium,
        Team,
        Crop,
        BringForward,
        SendBackward,
        Endnote,
        BinaryNumber,
        CurlyBraces,
        Bullseye,
        CloudServer,
        ClipboardFile,
        BackwardTen,
        ForwardTen,
        Vector,
        LayoutTwoColumns,
        LayoutTwoRows,
        LayoutThreeColumns,
        LayoutThreeRows,
        LayoutBottomRowTwoTiles,
        LayoutBottomRowThreeTiles,
        LayoutLeftColumnTwoTiles,
        LayoutLeftColumnThreeTiles,
        LayoutRightColumnTwoTiles,
        LayoutRightColumnThreeTiles,
        LayoutTopRowTwoTiles,
        LayoutTopRowThreeTiles,
        CssStyle,
        DataSync,
        Excavator,
        TableSync,
        DataSearch,
        Output,
        RangeRing,
        BlockPromote,
        Cubes,
        Hexagon,
        Package,
        Pill,
        ServerInstall,
        Server,
        TagAdd,
        TagPromote,
        TagRefresh,
        TagUndo,
        Tags,
        WrenchRedo,
        WrenchSnooze,
        WrenchTime,
        Panel,
        GlobeNetworkAdd,
        CubeEdit,
        FighterJet,
        LinkedSquares,
        BritishPound,
        ArrowsArc,
        RotateCw,
        RotateCcw,
        ThAdd,
        ThListAdd,
        ThVirtual,
        ThVirtualAdd,
        FilterSortAsc,
        FilterSortDesc,
        ObjectView,
        DataCloud,
        SubtractRightJoin,
        RunHistory,
        ArrayObject,
        Construction,
        Announcement,
        PhoneSearch,
        NotificationsAdd,
        SelectionBox,
        SelectionBoxAdd,
        SelectionBoxEdit,
        Pistol,
        AddChild,
        AddParent,
        RootFolder,
        DocumentCode,
        DocumentLocked,
        GiftBox,
        DeleteClip,
        Sweep,
        PageBreak,
        BranchLocked,
        BranchUnlocked,
        SelectionBoxRemove,
        Markdown,
        RefreshOff,
        VariableLayer,
        GitRebase,
        ConsoleAlert,
        WrapLines,
        Won,
        Yen,
        Drone,
        DroneUav,
        Spin,
        FunctionMinimal,
        CubeCutout,
        CubeCutouts,
        ForkEnd,
        AddApplication,
        AddDerivedColumn,
        AddTile,
        CircleDashed,
        Descendant,
        Engagement,
        NewComment,
        OuterJoin,
        Popout,
        FrameToFrame,
        CrystalBall,
    )
}
