// Generated by scripts/generate_tokens.py. Do not edit by hand.
// Source: tokens/v1/brace.tokens.json (SHA-256 4245588bea5e04927c7e8bd509ff06aa8b6a70b039a60bd82b711e5dc38b36e6)
package io.github.braceandroid.foundation

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** Primitive colors from the platform-neutral v1 token source. */
@Immutable
data class BracePalette(
    val amber200: Color,
    val amber50: Color,
    val amber700: Color,
    val amber900: Color,
    val black: Color,
    val green200: Color,
    val green50: Color,
    val green700: Color,
    val green900: Color,
    val indigo100: Color,
    val indigo200: Color,
    val indigo300: Color,
    val indigo400: Color,
    val indigo50: Color,
    val indigo500: Color,
    val indigo600: Color,
    val indigo700: Color,
    val indigo800: Color,
    val indigo900: Color,
    val red100: Color,
    val red200: Color,
    val red50: Color,
    val red700: Color,
    val red900: Color,
    val red950: Color,
    val slate0: Color,
    val slate100: Color,
    val slate200: Color,
    val slate25: Color,
    val slate300: Color,
    val slate400: Color,
    val slate50: Color,
    val slate500: Color,
    val slate600: Color,
    val slate700: Color,
    val slate800: Color,
    val slate900: Color,
    val slate950: Color,
    val transparent: Color,
)

/** Semantic colors. Consume these roles instead of palette values in UI code. */
@Immutable
data class BraceSemanticColors(
    val background: Color,
    val border: Color,
    val borderStrong: Color,
    val danger: Color,
    val dangerHover: Color,
    val dangerPressed: Color,
    val dangerSubtle: Color,
    val disabledContainer: Color,
    val disabledContent: Color,
    val focusRing: Color,
    val hover: Color,
    val inverseSurface: Color,
    val onBackground: Color,
    val onDanger: Color,
    val onDangerSubtle: Color,
    val onInverseSurface: Color,
    val onPrimary: Color,
    val onPrimarySubtle: Color,
    val onSelection: Color,
    val onSuccess: Color,
    val onSuccessSubtle: Color,
    val onSurface: Color,
    val onSurfaceMuted: Color,
    val onWarning: Color,
    val onWarningSubtle: Color,
    val pressed: Color,
    val primary: Color,
    val primaryHover: Color,
    val primaryPressed: Color,
    val primarySubtle: Color,
    val scrim: Color,
    val selection: Color,
    val success: Color,
    val successSubtle: Color,
    val surface: Color,
    val surfaceInset: Color,
    val surfaceRaised: Color,
    val tableAlternateRow: Color,
    val warning: Color,
    val warningSubtle: Color,
)

/** Nullable semantic overrides for a nested [BraceTheme] scope. */
@Immutable
data class BraceSemanticColorOverrides(
    val background: Color? = null,
    val border: Color? = null,
    val borderStrong: Color? = null,
    val danger: Color? = null,
    val dangerHover: Color? = null,
    val dangerPressed: Color? = null,
    val dangerSubtle: Color? = null,
    val disabledContainer: Color? = null,
    val disabledContent: Color? = null,
    val focusRing: Color? = null,
    val hover: Color? = null,
    val inverseSurface: Color? = null,
    val onBackground: Color? = null,
    val onDanger: Color? = null,
    val onDangerSubtle: Color? = null,
    val onInverseSurface: Color? = null,
    val onPrimary: Color? = null,
    val onPrimarySubtle: Color? = null,
    val onSelection: Color? = null,
    val onSuccess: Color? = null,
    val onSuccessSubtle: Color? = null,
    val onSurface: Color? = null,
    val onSurfaceMuted: Color? = null,
    val onWarning: Color? = null,
    val onWarningSubtle: Color? = null,
    val pressed: Color? = null,
    val primary: Color? = null,
    val primaryHover: Color? = null,
    val primaryPressed: Color? = null,
    val primarySubtle: Color? = null,
    val scrim: Color? = null,
    val selection: Color? = null,
    val success: Color? = null,
    val successSubtle: Color? = null,
    val surface: Color? = null,
    val surfaceInset: Color? = null,
    val surfaceRaised: Color? = null,
    val tableAlternateRow: Color? = null,
    val warning: Color? = null,
    val warningSubtle: Color? = null,
)

internal fun BraceSemanticColors.withOverrides(overrides: BraceSemanticColorOverrides) = copy(
    background = overrides.background ?: background,
    border = overrides.border ?: border,
    borderStrong = overrides.borderStrong ?: borderStrong,
    danger = overrides.danger ?: danger,
    dangerHover = overrides.dangerHover ?: dangerHover,
    dangerPressed = overrides.dangerPressed ?: dangerPressed,
    dangerSubtle = overrides.dangerSubtle ?: dangerSubtle,
    disabledContainer = overrides.disabledContainer ?: disabledContainer,
    disabledContent = overrides.disabledContent ?: disabledContent,
    focusRing = overrides.focusRing ?: focusRing,
    hover = overrides.hover ?: hover,
    inverseSurface = overrides.inverseSurface ?: inverseSurface,
    onBackground = overrides.onBackground ?: onBackground,
    onDanger = overrides.onDanger ?: onDanger,
    onDangerSubtle = overrides.onDangerSubtle ?: onDangerSubtle,
    onInverseSurface = overrides.onInverseSurface ?: onInverseSurface,
    onPrimary = overrides.onPrimary ?: onPrimary,
    onPrimarySubtle = overrides.onPrimarySubtle ?: onPrimarySubtle,
    onSelection = overrides.onSelection ?: onSelection,
    onSuccess = overrides.onSuccess ?: onSuccess,
    onSuccessSubtle = overrides.onSuccessSubtle ?: onSuccessSubtle,
    onSurface = overrides.onSurface ?: onSurface,
    onSurfaceMuted = overrides.onSurfaceMuted ?: onSurfaceMuted,
    onWarning = overrides.onWarning ?: onWarning,
    onWarningSubtle = overrides.onWarningSubtle ?: onWarningSubtle,
    pressed = overrides.pressed ?: pressed,
    primary = overrides.primary ?: primary,
    primaryHover = overrides.primaryHover ?: primaryHover,
    primaryPressed = overrides.primaryPressed ?: primaryPressed,
    primarySubtle = overrides.primarySubtle ?: primarySubtle,
    scrim = overrides.scrim ?: scrim,
    selection = overrides.selection ?: selection,
    success = overrides.success ?: success,
    successSubtle = overrides.successSubtle ?: successSubtle,
    surface = overrides.surface ?: surface,
    surfaceInset = overrides.surfaceInset ?: surfaceInset,
    surfaceRaised = overrides.surfaceRaised ?: surfaceRaised,
    tableAlternateRow = overrides.tableAlternateRow ?: tableAlternateRow,
    warning = overrides.warning ?: warning,
    warningSubtle = overrides.warningSubtle ?: warningSubtle,
)

/** Color roles and visual states for button components. */
@Immutable
data class BraceButtonColors(
    val dangerContainer: Color,
    val dangerContent: Color,
    val dangerHoverContainer: Color,
    val dangerPressedContainer: Color,
    val disabledContainer: Color,
    val disabledContent: Color,
    val focusRing: Color,
    val primaryContainer: Color,
    val primaryContent: Color,
    val primaryHoverContainer: Color,
    val primaryPressedContainer: Color,
    val secondaryBorder: Color,
    val secondaryContainer: Color,
    val secondaryContent: Color,
    val secondaryHoverContainer: Color,
    val secondaryPressedContainer: Color,
)

/** Color roles and visual states for callout components. */
@Immutable
data class BraceCalloutColors(
    val dangerContainer: Color,
    val dangerContent: Color,
    val neutralContainer: Color,
    val neutralContent: Color,
    val primaryContainer: Color,
    val primaryContent: Color,
    val successContainer: Color,
    val successContent: Color,
    val warningContainer: Color,
    val warningContent: Color,
)

/** Color roles and visual states for card components. */
@Immutable
data class BraceCardColors(
    val border: Color,
    val container: Color,
    val content: Color,
)

/** Color roles and visual states for checkbox components. */
@Immutable
data class BraceCheckboxColors(
    val checkedContainer: Color,
    val checkmark: Color,
    val disabledContainer: Color,
    val disabledContent: Color,
    val focusRing: Color,
    val uncheckedBorder: Color,
    val uncheckedContainer: Color,
)

/** Color roles and visual states for controlCard components. */
@Immutable
data class BraceControlCardColors(
    val border: Color,
    val container: Color,
    val content: Color,
    val disabledContainer: Color,
    val disabledContent: Color,
    val disabledSwitchThumb: Color,
    val disabledSwitchTrack: Color,
    val focusRing: Color,
    val hoverContainer: Color,
    val mutedContent: Color,
    val pressedContainer: Color,
    val radioDot: Color,
    val radioRing: Color,
    val radioSelectedRing: Color,
    val selectedBorder: Color,
    val selectedContainer: Color,
    val selectedContent: Color,
)

/** Color roles and visual states for dateInput components. */
@Immutable
data class BraceDateInputColors(
    val border: Color,
    val calendarIcon: Color,
    val container: Color,
    val content: Color,
    val disabledContainer: Color,
    val disabledContent: Color,
    val errorBorder: Color,
    val focusRing: Color,
    val focusedBorder: Color,
    val placeholder: Color,
)

/** Color roles and visual states for datePicker components. */
@Immutable
data class BraceDatePickerColors(
    val border: Color,
    val container: Color,
    val content: Color,
    val disabledContent: Color,
    val focusRing: Color,
    val hoverContainer: Color,
    val mutedContent: Color,
    val selectedContainer: Color,
    val selectedContent: Color,
    val todayBorder: Color,
)

/** Color roles and visual states for dateRangeInput components. */
@Immutable
data class BraceDateRangeInputColors(
    val border: Color,
    val calendarIcon: Color,
    val container: Color,
    val content: Color,
    val disabledContainer: Color,
    val disabledContent: Color,
    val errorBorder: Color,
    val focusRing: Color,
    val focusedBorder: Color,
    val placeholder: Color,
)

/** Color roles and visual states for dateRangePicker components. */
@Immutable
data class BraceDateRangePickerColors(
    val border: Color,
    val container: Color,
    val content: Color,
    val disabledContent: Color,
    val focusRing: Color,
    val hoverContainer: Color,
    val mutedContent: Color,
    val rangeContainer: Color,
    val rangeContent: Color,
    val selectedContainer: Color,
    val selectedContent: Color,
    val todayBorder: Color,
)

/** Color roles and visual states for dialog components. */
@Immutable
data class BraceDialogColors(
    val container: Color,
    val content: Color,
    val scrim: Color,
)

/** Color roles and visual states for drawer components. */
@Immutable
data class BraceDrawerColors(
    val border: Color,
    val container: Color,
    val content: Color,
)

/** Color roles and visual states for entityTitle components. */
@Immutable
data class BraceEntityTitleColors(
    val focusRing: Color,
    val icon: Color,
    val interactiveHover: Color,
    val interactivePressed: Color,
    val interactiveTitle: Color,
    val loadingContainer: Color,
    val subtitle: Color,
    val title: Color,
)

/** Color roles and visual states for input components. */
@Immutable
data class BraceInputColors(
    val border: Color,
    val container: Color,
    val content: Color,
    val disabledContainer: Color,
    val disabledContent: Color,
    val errorBorder: Color,
    val focusedBorder: Color,
    val placeholder: Color,
    val selection: Color,
)

/** Color roles and visual states for menu components. */
@Immutable
data class BraceMenuColors(
    val container: Color,
    val itemContent: Color,
    val itemHover: Color,
    val itemSelected: Color,
    val shortcutContent: Color,
)

/** Color roles and visual states for panelStack components. */
@Immutable
data class BracePanelStackColors(
    val backContent: Color,
    val backHover: Color,
    val backPressed: Color,
    val border: Color,
    val container: Color,
    val focusRing: Color,
    val header: Color,
    val title: Color,
)

/** Color roles and visual states for popover components. */
@Immutable
data class BracePopoverColors(
    val border: Color,
    val container: Color,
    val content: Color,
)

/** Color roles and visual states for progress components. */
@Immutable
data class BraceProgressColors(
    val dangerIndicator: Color,
    val disabledIndicator: Color,
    val indicator: Color,
    val successIndicator: Color,
    val track: Color,
    val warningIndicator: Color,
)

/** Color roles and visual states for radio components. */
@Immutable
data class BraceRadioColors(
    val container: Color,
    val disabledContainer: Color,
    val disabledContent: Color,
    val focusRing: Color,
    val hoverBorder: Color,
    val pressedBorder: Color,
    val selectedBorder: Color,
    val selectedDot: Color,
    val unselectedBorder: Color,
)

/** Color roles and visual states for segmentedControl components. */
@Immutable
data class BraceSegmentedControlColors(
    val border: Color,
    val container: Color,
    val disabledContainer: Color,
    val disabledContent: Color,
    val focusRing: Color,
    val hoverContainer: Color,
    val pressedContainer: Color,
    val selectedBorder: Color,
    val selectedContainer: Color,
    val selectedContent: Color,
    val selectedHoverContainer: Color,
    val selectedPressedContainer: Color,
    val selectedPrimaryContainer: Color,
    val selectedPrimaryContent: Color,
    val selectedPrimaryHoverContainer: Color,
    val selectedPrimaryPressedContainer: Color,
    val unselectedContainer: Color,
    val unselectedContent: Color,
)

/** Color roles and visual states for select components. */
@Immutable
data class BraceSelectColors(
    val activeContainer: Color,
    val container: Color,
    val content: Color,
    val disabledContent: Color,
    val focusRing: Color,
    val mutedContent: Color,
    val searchBorder: Color,
    val searchContainer: Color,
    val selectedContainer: Color,
    val selectedContent: Color,
)

/** Color roles and visual states for shortcut components. */
@Immutable
data class BraceShortcutColors(
    val border: Color,
    val container: Color,
    val content: Color,
)

/** Color roles and visual states for skeleton components. */
@Immutable
data class BraceSkeletonColors(
    val base: Color,
    val border: Color,
    val highlight: Color,
)

/** Color roles and visual states for slider components. */
@Immutable
data class BraceSliderColors(
    val activeTick: Color,
    val activeTrack: Color,
    val disabledActiveTrack: Color,
    val disabledInactiveTrack: Color,
    val disabledThumb: Color,
    val focusRing: Color,
    val inactiveTick: Color,
    val inactiveTrack: Color,
    val label: Color,
    val mutedLabel: Color,
    val thumb: Color,
    val thumbPressed: Color,
)

/** Color roles and visual states for spinner components. */
@Immutable
data class BraceSpinnerColors(
    val dangerIndicator: Color,
    val indicator: Color,
    val successIndicator: Color,
    val track: Color,
    val warningIndicator: Color,
)

/** Color roles and visual states for switch components. */
@Immutable
data class BraceSwitchColors(
    val checkedTrack: Color,
    val disabledThumb: Color,
    val disabledTrack: Color,
    val focusRing: Color,
    val thumb: Color,
    val uncheckedTrack: Color,
)

/** Color roles and visual states for table components. */
@Immutable
data class BraceTableColors(
    val alternateRow: Color,
    val editorBackground: Color,
    val editorBorder: Color,
    val editorErrorBorder: Color,
    val editorText: Color,
    val gridLine: Color,
    val header: Color,
    val headerContent: Color,
    val resizeHandle: Color,
    val row: Color,
    val selectedRow: Color,
)

/** Color roles and visual states for tag components. */
@Immutable
data class BraceTagColors(
    val border: Color,
    val container: Color,
    val content: Color,
)

/** Color roles and visual states for timeInput components. */
@Immutable
data class BraceTimeInputColors(
    val border: Color,
    val clockIcon: Color,
    val container: Color,
    val content: Color,
    val disabledContainer: Color,
    val disabledContent: Color,
    val errorBorder: Color,
    val focusRing: Color,
    val focusedBorder: Color,
    val placeholder: Color,
)

/** Color roles and visual states for timePicker components. */
@Immutable
data class BraceTimePickerColors(
    val border: Color,
    val container: Color,
    val content: Color,
    val disabledContent: Color,
    val errorBorder: Color,
    val focusRing: Color,
    val hoverContainer: Color,
    val mutedContent: Color,
    val stepContainer: Color,
    val stepContent: Color,
)

/** Color roles and visual states for timeZoneSelect components. */
@Immutable
data class BraceTimeZoneSelectColors(
    val activeContainer: Color,
    val border: Color,
    val container: Color,
    val content: Color,
    val disabledContent: Color,
    val focusRing: Color,
    val mutedContent: Color,
    val searchBorder: Color,
    val searchContainer: Color,
    val selectedContainer: Color,
    val selectedContent: Color,
)

/** Color roles and visual states for toast components. */
@Immutable
data class BraceToastColors(
    val border: Color,
    val dangerContainer: Color,
    val dangerContent: Color,
    val focusRing: Color,
    val neutralContainer: Color,
    val neutralContent: Color,
    val primaryContainer: Color,
    val primaryContent: Color,
    val successContainer: Color,
    val successContent: Color,
    val warningContainer: Color,
    val warningContent: Color,
)

/** Color roles and visual states for tooltip components. */
@Immutable
data class BraceTooltipColors(
    val border: Color,
    val container: Color,
    val content: Color,
)

/** Color roles and visual states for topBar components. */
@Immutable
data class BraceTopBarColors(
    val border: Color,
    val container: Color,
    val divider: Color,
    val title: Color,
)

/** Color roles and visual states for tree components. */
@Immutable
data class BraceTreeColors(
    val caret: Color,
    val container: Color,
    val content: Color,
    val disabledContent: Color,
    val focusRing: Color,
    val hoverContainer: Color,
    val mutedContent: Color,
    val selectedContainer: Color,
    val selectedContent: Color,
)

/** Color tokens for all component families. */
@Immutable
data class BraceComponentColors(
    val button: BraceButtonColors,
    val callout: BraceCalloutColors,
    val card: BraceCardColors,
    val checkbox: BraceCheckboxColors,
    val controlCard: BraceControlCardColors,
    val dateInput: BraceDateInputColors,
    val datePicker: BraceDatePickerColors,
    val dateRangeInput: BraceDateRangeInputColors,
    val dateRangePicker: BraceDateRangePickerColors,
    val dialog: BraceDialogColors,
    val drawer: BraceDrawerColors,
    val entityTitle: BraceEntityTitleColors,
    val input: BraceInputColors,
    val menu: BraceMenuColors,
    val panelStack: BracePanelStackColors,
    val popover: BracePopoverColors,
    val progress: BraceProgressColors,
    val radio: BraceRadioColors,
    val segmentedControl: BraceSegmentedControlColors,
    val select: BraceSelectColors,
    val shortcut: BraceShortcutColors,
    val skeleton: BraceSkeletonColors,
    val slider: BraceSliderColors,
    val spinner: BraceSpinnerColors,
    val switch: BraceSwitchColors,
    val table: BraceTableColors,
    val tag: BraceTagColors,
    val timeInput: BraceTimeInputColors,
    val timePicker: BraceTimePickerColors,
    val timeZoneSelect: BraceTimeZoneSelectColors,
    val toast: BraceToastColors,
    val tooltip: BraceTooltipColors,
    val topBar: BraceTopBarColors,
    val tree: BraceTreeColors,
)

@Immutable
data class BraceColorScheme(
    val semantic: BraceSemanticColors,
    val components: BraceComponentColors,
)

/** spacingDp values in Android dp. */
@Immutable
data class BraceSpacingTokens(
    val lg: Dp,
    val md: Dp,
    val none: Dp,
    val sm: Dp,
    val xl: Dp,
    val xs: Dp,
    val xxl: Dp,
    val xxs: Dp,
    val xxxl: Dp,
)

/** sizingDp values in Android dp. */
@Immutable
data class BraceSizingTokens(
    val borderStrongWidth: Dp,
    val borderWidth: Dp,
    val focusRingWidth: Dp,
    val iconLg: Dp,
    val iconMd: Dp,
    val iconSm: Dp,
    val overlayMaxWidth: Dp,
    val tableMinColumnWidth: Dp,
    val touchTarget: Dp,
)

/** shapeDp values in Android dp. */
@Immutable
data class BraceShapeTokens(
    val lg: Dp,
    val md: Dp,
    val none: Dp,
    val pill: Dp,
    val sm: Dp,
    val xs: Dp,
)

/** elevationDp values in Android dp. */
@Immutable
data class BraceElevationTokens(
    val floating: Dp,
    val modal: Dp,
    val none: Dp,
    val raised: Dp,
)

/** Animation durations in milliseconds. Reduced motion resolves all durations to zero. */
@Immutable
data class BraceMotionTokens(
    val fast: Int,
    val instant: Int,
    val normal: Int,
    val slow: Int,
)

/** Control and layout measures for the selected density. Touch targets remain 48 dp. */
@Immutable
data class BraceDensityTokens(
    val contentPaddingDp: Dp,
    val controlHeightDp: Dp,
    val itemGapDp: Dp,
    val rowHeightDp: Dp,
)

/** Dimensional tokens for button components. */
@Immutable
data class BraceButtonMetrics(
    val cornerRadius: Dp,
    val horizontalPadding: Dp,
    val iconGap: Dp,
)

/** Dimensional tokens for callout components. */
@Immutable
data class BraceCalloutMetrics(
    val accentWidth: Dp,
    val contentPadding: Dp,
    val cornerRadius: Dp,
)

/** Dimensional tokens for card components. */
@Immutable
data class BraceCardMetrics(
    val contentPadding: Dp,
    val cornerRadius: Dp,
)

/** Dimensional tokens for checkbox components. */
@Immutable
data class BraceCheckboxMetrics(
    val cornerRadius: Dp,
    val focusCornerRadius: Dp,
    val size: Dp,
    val strokeWidth: Dp,
)

/** Dimensional tokens for controlCard components. */
@Immutable
data class BraceControlCardMetrics(
    val contentPadding: Dp,
    val cornerRadius: Dp,
    val descriptionGap: Dp,
    val indicatorGap: Dp,
    val radioDotRadius: Dp,
    val radioSize: Dp,
    val radioStrokeWidth: Dp,
)

/** Dimensional tokens for dateInput components. */
@Immutable
data class BraceDateInputMetrics(
    val borderWidth: Dp,
    val cornerRadius: Dp,
    val horizontalPadding: Dp,
)

/** Dimensional tokens for datePicker components. */
@Immutable
data class BraceDatePickerMetrics(
    val columnGap: Dp,
    val contentPadding: Dp,
    val cornerRadius: Dp,
    val daySize: Dp,
)

/** Dimensional tokens for dateRangeInput components. */
@Immutable
data class BraceDateRangeInputMetrics(
    val borderWidth: Dp,
    val cornerRadius: Dp,
    val fieldGap: Dp,
    val horizontalPadding: Dp,
)

/** Dimensional tokens for dateRangePicker components. */
@Immutable
data class BraceDateRangePickerMetrics(
    val columnGap: Dp,
    val contentPadding: Dp,
    val cornerRadius: Dp,
    val daySize: Dp,
    val monthGap: Dp,
    val twoMonthMinWidth: Dp,
)

/** Dimensional tokens for dialog components. */
@Immutable
data class BraceDialogMetrics(
    val contentPadding: Dp,
    val cornerRadius: Dp,
)

/** Dimensional tokens for drawer components. */
@Immutable
data class BraceDrawerMetrics(
    val contentPadding: Dp,
    val cornerRadius: Dp,
    val maxWidth: Dp,
)

/** Dimensional tokens for entityTitle components. */
@Immutable
data class BraceEntityTitleMetrics(
    val iconGap: Dp,
    val iconSize: Dp,
    val loadingCornerRadius: Dp,
    val loadingSubtitleHeight: Dp,
    val loadingSubtitleWidth: Dp,
    val loadingTitleHeight: Dp,
    val loadingTitleWidth: Dp,
    val subtitleGap: Dp,
    val titleTagsGap: Dp,
)

/** Dimensional tokens for input components. */
@Immutable
data class BraceInputMetrics(
    val borderWidth: Dp,
    val cornerRadius: Dp,
    val horizontalPadding: Dp,
)

/** Dimensional tokens for menu components. */
@Immutable
data class BraceMenuMetrics(
    val cornerRadius: Dp,
    val itemHorizontalPadding: Dp,
)

/** Dimensional tokens for panelStack components. */
@Immutable
data class BracePanelStackMetrics(
    val backMaxWidth: Dp,
    val horizontalPadding: Dp,
    val itemGap: Dp,
    val minHeight: Dp,
    val verticalPadding: Dp,
)

/** Dimensional tokens for popover components. */
@Immutable
data class BracePopoverMetrics(
    val contentPadding: Dp,
    val cornerRadius: Dp,
    val maxWidth: Dp,
)

/** Dimensional tokens for progress components. */
@Immutable
data class BraceProgressMetrics(
    val cornerRadius: Dp,
    val trackHeight: Dp,
)

/** Dimensional tokens for radio components. */
@Immutable
data class BraceRadioMetrics(
    val dotRadius: Dp,
    val size: Dp,
    val strokeWidth: Dp,
)

/** Dimensional tokens for segmentedControl components. */
@Immutable
data class BraceSegmentedControlMetrics(
    val cornerRadius: Dp,
    val gap: Dp,
    val horizontalPadding: Dp,
    val itemCornerRadius: Dp,
)

/** Dimensional tokens for select components. */
@Immutable
data class BraceSelectMetrics(
    val cornerRadius: Dp,
    val maxListHeight: Dp,
    val minWidth: Dp,
    val optionHorizontalPadding: Dp,
    val searchHorizontalPadding: Dp,
)

/** Dimensional tokens for shortcut components. */
@Immutable
data class BraceShortcutMetrics(
    val cornerRadius: Dp,
    val horizontalPadding: Dp,
    val verticalPadding: Dp,
)

/** Dimensional tokens for skeleton components. */
@Immutable
data class BraceSkeletonMetrics(
    val cornerRadius: Dp,
    val lineHeight: Dp,
)

/** Dimensional tokens for slider components. */
@Immutable
data class BraceSliderMetrics(
    val axisLabelGap: Dp,
    val focusCornerRadius: Dp,
    val minHeight: Dp,
    val thumbHeight: Dp,
    val thumbSlotWidth: Dp,
    val thumbWidth: Dp,
)

/** Dimensional tokens for spinner components. */
@Immutable
data class BraceSpinnerMetrics(
    val largeSize: Dp,
    val mediumSize: Dp,
    val smallSize: Dp,
    val strokeWidth: Dp,
)

/** Dimensional tokens for switch components. */
@Immutable
data class BraceSwitchMetrics(
    val focusCornerRadius: Dp,
    val thumbInset: Dp,
    val thumbRadius: Dp,
    val trackHeight: Dp,
    val trackWidth: Dp,
)

/** Dimensional tokens for table components. */
@Immutable
data class BraceTableMetrics(
    val cellHorizontalPadding: Dp,
    val gridLineWidth: Dp,
    val resizeHandleWidth: Dp,
)

/** Dimensional tokens for tag components. */
@Immutable
data class BraceTagMetrics(
    val cornerRadius: Dp,
    val horizontalPadding: Dp,
)

/** Dimensional tokens for timeInput components. */
@Immutable
data class BraceTimeInputMetrics(
    val borderWidth: Dp,
    val cornerRadius: Dp,
    val horizontalPadding: Dp,
)

/** Dimensional tokens for timePicker components. */
@Immutable
data class BraceTimePickerMetrics(
    val borderWidth: Dp,
    val columnGap: Dp,
    val contentPadding: Dp,
    val cornerRadius: Dp,
    val unitWidth: Dp,
)

/** Dimensional tokens for timeZoneSelect components. */
@Immutable
data class BraceTimeZoneSelectMetrics(
    val cornerRadius: Dp,
    val horizontalPadding: Dp,
    val listMaxHeight: Dp,
    val minWidth: Dp,
    val rowHeight: Dp,
)

/** Dimensional tokens for toast components. */
@Immutable
data class BraceToastMetrics(
    val contentPadding: Dp,
    val cornerRadius: Dp,
    val iconGap: Dp,
    val maxWidth: Dp,
)

/** Dimensional tokens for tooltip components. */
@Immutable
data class BraceTooltipMetrics(
    val contentPadding: Dp,
    val cornerRadius: Dp,
    val maxWidth: Dp,
)

/** Dimensional tokens for topBar components. */
@Immutable
data class BraceTopBarMetrics(
    val dividerHeight: Dp,
    val groupGap: Dp,
    val horizontalPadding: Dp,
    val minHeight: Dp,
    val verticalPadding: Dp,
)

/** Dimensional tokens for tree components. */
@Immutable
data class BraceTreeMetrics(
    val cornerRadius: Dp,
    val horizontalPadding: Dp,
    val indent: Dp,
)

/** Dimensional tokens for all component families. */
@Immutable
data class BraceComponentMetrics(
    val button: BraceButtonMetrics,
    val callout: BraceCalloutMetrics,
    val card: BraceCardMetrics,
    val checkbox: BraceCheckboxMetrics,
    val controlCard: BraceControlCardMetrics,
    val dateInput: BraceDateInputMetrics,
    val datePicker: BraceDatePickerMetrics,
    val dateRangeInput: BraceDateRangeInputMetrics,
    val dateRangePicker: BraceDateRangePickerMetrics,
    val dialog: BraceDialogMetrics,
    val drawer: BraceDrawerMetrics,
    val entityTitle: BraceEntityTitleMetrics,
    val input: BraceInputMetrics,
    val menu: BraceMenuMetrics,
    val panelStack: BracePanelStackMetrics,
    val popover: BracePopoverMetrics,
    val progress: BraceProgressMetrics,
    val radio: BraceRadioMetrics,
    val segmentedControl: BraceSegmentedControlMetrics,
    val select: BraceSelectMetrics,
    val shortcut: BraceShortcutMetrics,
    val skeleton: BraceSkeletonMetrics,
    val slider: BraceSliderMetrics,
    val spinner: BraceSpinnerMetrics,
    val switch: BraceSwitchMetrics,
    val table: BraceTableMetrics,
    val tag: BraceTagMetrics,
    val timeInput: BraceTimeInputMetrics,
    val timePicker: BraceTimePickerMetrics,
    val timeZoneSelect: BraceTimeZoneSelectMetrics,
    val toast: BraceToastMetrics,
    val tooltip: BraceTooltipMetrics,
    val topBar: BraceTopBarMetrics,
    val tree: BraceTreeMetrics,
)

/** Primitive scalable font sizes. */
@Immutable
data class BraceFontSizeTokens(
    val lg: TextUnit,
    val md: TextUnit,
    val sm: TextUnit,
    val xl: TextUnit,
    val xs: TextUnit,
    val xxl: TextUnit,
)

/** Primitive scalable line heights. */
@Immutable
data class BraceLineHeightTokens(
    val display: TextUnit,
    val normal: TextUnit,
    val relaxed: TextUnit,
    val tight: TextUnit,
)

/** Named font weights. */
@Immutable
data class BraceFontWeightTokens(
    val bold: FontWeight,
    val medium: FontWeight,
    val regular: FontWeight,
    val semibold: FontWeight,
)

/** Named font families. */
@Immutable
data class BraceFontFamilyTokens(
    val body: FontFamily,
    val mono: FontFamily,
)

/** Primitive type scale for custom text styles. */
@Immutable
data class BraceTypeScaleTokens(
    val fontFamilies: BraceFontFamilyTokens,
    val fontSizes: BraceFontSizeTokens,
    val lineHeights: BraceLineHeightTokens,
    val weights: BraceFontWeightTokens,
)

/** Named Compose text styles generated from platform-neutral type tokens. */
@Immutable
data class BraceTypographyTokens(
    val body: TextStyle,
    val bodyStrong: TextStyle,
    val caption: TextStyle,
    val code: TextStyle,
    val display: TextStyle,
    val label: TextStyle,
    val subtitle: TextStyle,
    val title: TextStyle,
)

internal fun buildBraceComponentColors(semantic: BraceSemanticColors) = BraceComponentColors(
    button = BraceButtonColors(
        dangerContainer = semantic.danger,
        dangerContent = semantic.onDanger,
        dangerHoverContainer = semantic.dangerHover,
        dangerPressedContainer = semantic.dangerPressed,
        disabledContainer = semantic.disabledContainer,
        disabledContent = semantic.disabledContent,
        focusRing = semantic.focusRing,
        primaryContainer = semantic.primary,
        primaryContent = semantic.onPrimary,
        primaryHoverContainer = semantic.primaryHover,
        primaryPressedContainer = semantic.primaryPressed,
        secondaryBorder = semantic.borderStrong,
        secondaryContainer = semantic.surface,
        secondaryContent = semantic.onSurface,
        secondaryHoverContainer = semantic.hover,
        secondaryPressedContainer = semantic.pressed,
    ),
    callout = BraceCalloutColors(
        dangerContainer = semantic.dangerSubtle,
        dangerContent = semantic.onDangerSubtle,
        neutralContainer = semantic.surfaceInset,
        neutralContent = semantic.onSurface,
        primaryContainer = semantic.primarySubtle,
        primaryContent = semantic.onPrimarySubtle,
        successContainer = semantic.successSubtle,
        successContent = semantic.onSuccessSubtle,
        warningContainer = semantic.warningSubtle,
        warningContent = semantic.onWarningSubtle,
    ),
    card = BraceCardColors(
        border = semantic.border,
        container = semantic.surfaceRaised,
        content = semantic.onSurface,
    ),
    checkbox = BraceCheckboxColors(
        checkedContainer = semantic.primary,
        checkmark = semantic.onPrimary,
        disabledContainer = semantic.disabledContainer,
        disabledContent = semantic.disabledContent,
        focusRing = semantic.focusRing,
        uncheckedBorder = semantic.borderStrong,
        uncheckedContainer = semantic.surface,
    ),
    controlCard = BraceControlCardColors(
        border = semantic.border,
        container = semantic.surfaceRaised,
        content = semantic.onSurface,
        disabledContainer = semantic.disabledContainer,
        disabledContent = semantic.disabledContent,
        disabledSwitchThumb = semantic.surface,
        disabledSwitchTrack = semantic.disabledContent,
        focusRing = semantic.focusRing,
        hoverContainer = semantic.hover,
        mutedContent = semantic.onSurfaceMuted,
        pressedContainer = semantic.pressed,
        radioDot = semantic.primary,
        radioRing = semantic.borderStrong,
        radioSelectedRing = semantic.primary,
        selectedBorder = semantic.primary,
        selectedContainer = semantic.selection,
        selectedContent = semantic.onSelection,
    ),
    dateInput = BraceDateInputColors(
        border = semantic.border,
        calendarIcon = semantic.onSurface,
        container = semantic.surface,
        content = semantic.onSurface,
        disabledContainer = semantic.disabledContainer,
        disabledContent = semantic.disabledContent,
        errorBorder = semantic.danger,
        focusRing = semantic.focusRing,
        focusedBorder = semantic.focusRing,
        placeholder = semantic.onSurfaceMuted,
    ),
    datePicker = BraceDatePickerColors(
        border = semantic.border,
        container = semantic.surface,
        content = semantic.onSurface,
        disabledContent = semantic.disabledContent,
        focusRing = semantic.focusRing,
        hoverContainer = semantic.hover,
        mutedContent = semantic.onSurfaceMuted,
        selectedContainer = semantic.primary,
        selectedContent = semantic.onPrimary,
        todayBorder = semantic.primary,
    ),
    dateRangeInput = BraceDateRangeInputColors(
        border = semantic.border,
        calendarIcon = semantic.onSurface,
        container = semantic.surface,
        content = semantic.onSurface,
        disabledContainer = semantic.disabledContainer,
        disabledContent = semantic.disabledContent,
        errorBorder = semantic.danger,
        focusRing = semantic.focusRing,
        focusedBorder = semantic.focusRing,
        placeholder = semantic.onSurfaceMuted,
    ),
    dateRangePicker = BraceDateRangePickerColors(
        border = semantic.border,
        container = semantic.surface,
        content = semantic.onSurface,
        disabledContent = semantic.disabledContent,
        focusRing = semantic.focusRing,
        hoverContainer = semantic.hover,
        mutedContent = semantic.onSurfaceMuted,
        rangeContainer = semantic.selection,
        rangeContent = semantic.onSelection,
        selectedContainer = semantic.primary,
        selectedContent = semantic.onPrimary,
        todayBorder = semantic.primary,
    ),
    dialog = BraceDialogColors(
        container = semantic.surfaceRaised,
        content = semantic.onSurface,
        scrim = semantic.scrim,
    ),
    drawer = BraceDrawerColors(
        border = semantic.border,
        container = semantic.surfaceRaised,
        content = semantic.onSurface,
    ),
    entityTitle = BraceEntityTitleColors(
        focusRing = semantic.focusRing,
        icon = semantic.onSurfaceMuted,
        interactiveHover = semantic.primaryHover,
        interactivePressed = semantic.primaryPressed,
        interactiveTitle = semantic.primary,
        loadingContainer = semantic.disabledContainer,
        subtitle = semantic.onSurfaceMuted,
        title = semantic.onSurface,
    ),
    input = BraceInputColors(
        border = semantic.border,
        container = semantic.surface,
        content = semantic.onSurface,
        disabledContainer = semantic.disabledContainer,
        disabledContent = semantic.disabledContent,
        errorBorder = semantic.danger,
        focusedBorder = semantic.focusRing,
        placeholder = semantic.onSurfaceMuted,
        selection = semantic.selection,
    ),
    menu = BraceMenuColors(
        container = semantic.surfaceRaised,
        itemContent = semantic.onSurface,
        itemHover = semantic.hover,
        itemSelected = semantic.selection,
        shortcutContent = semantic.onSurfaceMuted,
    ),
    panelStack = BracePanelStackColors(
        backContent = semantic.onSurface,
        backHover = semantic.hover,
        backPressed = semantic.pressed,
        border = semantic.borderStrong,
        container = semantic.surfaceRaised,
        focusRing = semantic.focusRing,
        header = semantic.surfaceRaised,
        title = semantic.onSurface,
    ),
    popover = BracePopoverColors(
        border = semantic.border,
        container = semantic.surfaceRaised,
        content = semantic.onSurface,
    ),
    progress = BraceProgressColors(
        dangerIndicator = semantic.danger,
        disabledIndicator = semantic.disabledContent,
        indicator = semantic.primary,
        successIndicator = semantic.success,
        track = semantic.surfaceInset,
        warningIndicator = semantic.warning,
    ),
    radio = BraceRadioColors(
        container = semantic.surface,
        disabledContainer = semantic.disabledContainer,
        disabledContent = semantic.disabledContent,
        focusRing = semantic.focusRing,
        hoverBorder = semantic.primaryHover,
        pressedBorder = semantic.primaryPressed,
        selectedBorder = semantic.primary,
        selectedDot = semantic.primary,
        unselectedBorder = semantic.borderStrong,
    ),
    segmentedControl = BraceSegmentedControlColors(
        border = semantic.border,
        container = semantic.surfaceInset,
        disabledContainer = semantic.disabledContainer,
        disabledContent = semantic.disabledContent,
        focusRing = semantic.focusRing,
        hoverContainer = semantic.surfaceRaised,
        pressedContainer = semantic.pressed,
        selectedBorder = semantic.borderStrong,
        selectedContainer = semantic.surfaceRaised,
        selectedContent = semantic.onSurface,
        selectedHoverContainer = semantic.hover,
        selectedPressedContainer = semantic.pressed,
        selectedPrimaryContainer = semantic.primary,
        selectedPrimaryContent = semantic.onPrimary,
        selectedPrimaryHoverContainer = semantic.primaryHover,
        selectedPrimaryPressedContainer = semantic.primaryPressed,
        unselectedContainer = semantic.surfaceInset,
        unselectedContent = semantic.onSurface,
    ),
    select = BraceSelectColors(
        activeContainer = semantic.hover,
        container = semantic.surfaceRaised,
        content = semantic.onSurface,
        disabledContent = semantic.disabledContent,
        focusRing = semantic.focusRing,
        mutedContent = semantic.onSurfaceMuted,
        searchBorder = semantic.border,
        searchContainer = semantic.surface,
        selectedContainer = semantic.selection,
        selectedContent = semantic.onSelection,
    ),
    shortcut = BraceShortcutColors(
        border = semantic.borderStrong,
        container = semantic.surfaceInset,
        content = semantic.onSurface,
    ),
    skeleton = BraceSkeletonColors(
        base = semantic.disabledContainer,
        border = semantic.border,
        highlight = semantic.selection,
    ),
    slider = BraceSliderColors(
        activeTick = semantic.onPrimary,
        activeTrack = semantic.primary,
        disabledActiveTrack = semantic.disabledContent,
        disabledInactiveTrack = semantic.disabledContainer,
        disabledThumb = semantic.disabledContent,
        focusRing = semantic.focusRing,
        inactiveTick = semantic.surface,
        inactiveTrack = semantic.borderStrong,
        label = semantic.onSurface,
        mutedLabel = semantic.onSurfaceMuted,
        thumb = semantic.primary,
        thumbPressed = semantic.primaryHover,
    ),
    spinner = BraceSpinnerColors(
        dangerIndicator = semantic.danger,
        indicator = semantic.primary,
        successIndicator = semantic.success,
        track = semantic.surfaceInset,
        warningIndicator = semantic.warning,
    ),
    switch = BraceSwitchColors(
        checkedTrack = semantic.primary,
        disabledThumb = semantic.disabledContent,
        disabledTrack = semantic.disabledContainer,
        focusRing = semantic.focusRing,
        thumb = semantic.surface,
        uncheckedTrack = semantic.borderStrong,
    ),
    table = BraceTableColors(
        alternateRow = semantic.tableAlternateRow,
        editorBackground = semantic.surfaceRaised,
        editorBorder = semantic.focusRing,
        editorErrorBorder = semantic.danger,
        editorText = semantic.onSurface,
        gridLine = semantic.border,
        header = semantic.surfaceInset,
        headerContent = semantic.onSurface,
        resizeHandle = semantic.focusRing,
        row = semantic.surface,
        selectedRow = semantic.selection,
    ),
    tag = BraceTagColors(
        border = semantic.primary,
        container = semantic.primarySubtle,
        content = semantic.onPrimarySubtle,
    ),
    timeInput = BraceTimeInputColors(
        border = semantic.border,
        clockIcon = semantic.onSurface,
        container = semantic.surface,
        content = semantic.onSurface,
        disabledContainer = semantic.disabledContainer,
        disabledContent = semantic.disabledContent,
        errorBorder = semantic.danger,
        focusRing = semantic.focusRing,
        focusedBorder = semantic.focusRing,
        placeholder = semantic.onSurfaceMuted,
    ),
    timePicker = BraceTimePickerColors(
        border = semantic.border,
        container = semantic.surface,
        content = semantic.onSurface,
        disabledContent = semantic.disabledContent,
        errorBorder = semantic.danger,
        focusRing = semantic.focusRing,
        hoverContainer = semantic.hover,
        mutedContent = semantic.onSurfaceMuted,
        stepContainer = semantic.surfaceRaised,
        stepContent = semantic.onSurface,
    ),
    timeZoneSelect = BraceTimeZoneSelectColors(
        activeContainer = semantic.hover,
        border = semantic.border,
        container = semantic.surfaceRaised,
        content = semantic.onSurface,
        disabledContent = semantic.disabledContent,
        focusRing = semantic.focusRing,
        mutedContent = semantic.onSurfaceMuted,
        searchBorder = semantic.border,
        searchContainer = semantic.surface,
        selectedContainer = semantic.selection,
        selectedContent = semantic.onSelection,
    ),
    toast = BraceToastColors(
        border = semantic.borderStrong,
        dangerContainer = semantic.dangerSubtle,
        dangerContent = semantic.onDangerSubtle,
        focusRing = semantic.focusRing,
        neutralContainer = semantic.surfaceRaised,
        neutralContent = semantic.onSurface,
        primaryContainer = semantic.primarySubtle,
        primaryContent = semantic.onPrimarySubtle,
        successContainer = semantic.successSubtle,
        successContent = semantic.onSuccessSubtle,
        warningContainer = semantic.warningSubtle,
        warningContent = semantic.onWarningSubtle,
    ),
    tooltip = BraceTooltipColors(
        border = semantic.borderStrong,
        container = semantic.inverseSurface,
        content = semantic.onInverseSurface,
    ),
    topBar = BraceTopBarColors(
        border = semantic.borderStrong,
        container = semantic.surfaceRaised,
        divider = semantic.borderStrong,
        title = semantic.onSurface,
    ),
    tree = BraceTreeColors(
        caret = semantic.onSurfaceMuted,
        container = semantic.surface,
        content = semantic.onSurface,
        disabledContent = semantic.disabledContent,
        focusRing = semantic.focusRing,
        hoverContainer = semantic.hover,
        mutedContent = semantic.onSurfaceMuted,
        selectedContainer = semantic.selection,
        selectedContent = semantic.onSelection,
    ),
)

/** Generated defaults. The JSON source is also suitable for other platforms. */
object BraceTokenDefaults {
    const val version: String = "1.2.0"
    val palette = BracePalette(
        amber200 = Color(0xFFF9D88C),
        amber50 = Color(0xFFFFF7E1),
        amber700 = Color(0xFF875600),
        amber900 = Color(0xFF6D4500),
        black = Color(0xFF000000),
        green200 = Color(0xFFA3D9B7),
        green50 = Color(0xFFEAF8EF),
        green700 = Color(0xFF166C47),
        green900 = Color(0xFF0B5132),
        indigo100 = Color(0xFFDCE3FF),
        indigo200 = Color(0xFFC4D0FF),
        indigo300 = Color(0xFFA9B9FF),
        indigo400 = Color(0xFF8299F4),
        indigo50 = Color(0xFFEBEFFF),
        indigo500 = Color(0xFF5D78E9),
        indigo600 = Color(0xFF405DDC),
        indigo700 = Color(0xFF3654C6),
        indigo800 = Color(0xFF28439F),
        indigo900 = Color(0xFF17368D),
        red100 = Color(0xFFFAD3D0),
        red200 = Color(0xFFF5B2AA),
        red50 = Color(0xFFFDEDEC),
        red700 = Color(0xFFB3261E),
        red900 = Color(0xFF8C1A16),
        red950 = Color(0xFF701511),
        slate0 = Color(0xFFFFFFFF),
        slate100 = Color(0xFFE9EEF5),
        slate200 = Color(0xFFD5DEEA),
        slate25 = Color(0xFFF9FAFD),
        slate300 = Color(0xFFB8C5D6),
        slate400 = Color(0xFF92A2B8),
        slate50 = Color(0xFFF4F7FB),
        slate500 = Color(0xFF6B7D96),
        slate600 = Color(0xFF4D5F78),
        slate700 = Color(0xFF35455C),
        slate800 = Color(0xFF233146),
        slate900 = Color(0xFF162238),
        slate950 = Color(0xFF0C1422),
        transparent = Color(0x00000000),
    )

    private val lightSemantic = BraceSemanticColors(
        background = Color(0xFFF4F7FB),
        border = Color(0xFFB8C5D6),
        borderStrong = Color(0xFF4D5F78),
        danger = Color(0xFFB3261E),
        dangerHover = Color(0xFF8C1A16),
        dangerPressed = Color(0xFF701511),
        dangerSubtle = Color(0xFFFDEDEC),
        disabledContainer = Color(0xFFE9EEF5),
        disabledContent = Color(0xFF4D5F78),
        focusRing = Color(0xFF28439F),
        hover = Color(0xFFE9EEF5),
        inverseSurface = Color(0xFF162238),
        onBackground = Color(0xFF162238),
        onDanger = Color(0xFFFFFFFF),
        onDangerSubtle = Color(0xFF8C1A16),
        onInverseSurface = Color(0xFFFFFFFF),
        onPrimary = Color(0xFFFFFFFF),
        onPrimarySubtle = Color(0xFF17368D),
        onSelection = Color(0xFF17368D),
        onSuccess = Color(0xFFFFFFFF),
        onSuccessSubtle = Color(0xFF0B5132),
        onSurface = Color(0xFF162238),
        onSurfaceMuted = Color(0xFF4D5F78),
        onWarning = Color(0xFFFFFFFF),
        onWarningSubtle = Color(0xFF6D4500),
        pressed = Color(0xFFD5DEEA),
        primary = Color(0xFF3654C6),
        primaryHover = Color(0xFF28439F),
        primaryPressed = Color(0xFF17368D),
        primarySubtle = Color(0xFFEBEFFF),
        scrim = Color(0x990C1422),
        selection = Color(0xFFDCE3FF),
        success = Color(0xFF166C47),
        successSubtle = Color(0xFFEAF8EF),
        surface = Color(0xFFFFFFFF),
        surfaceInset = Color(0xFFE9EEF5),
        surfaceRaised = Color(0xFFFFFFFF),
        tableAlternateRow = Color(0xFFF9FAFD),
        warning = Color(0xFF875600),
        warningSubtle = Color(0xFFFFF7E1),
    )
    val light = BraceColorScheme(
        semantic = lightSemantic,
        components = buildBraceComponentColors(lightSemantic),
    )

    private val darkSemantic = BraceSemanticColors(
        background = Color(0xFF0C1422),
        border = Color(0xFF4D5F78),
        borderStrong = Color(0xFFB8C5D6),
        danger = Color(0xFFF5B2AA),
        dangerHover = Color(0xFFFAD3D0),
        dangerPressed = Color(0xFFFDEDEC),
        dangerSubtle = Color(0xFF8C1A16),
        disabledContainer = Color(0xFF233146),
        disabledContent = Color(0xFFB8C5D6),
        focusRing = Color(0xFFA9B9FF),
        hover = Color(0xFF233146),
        inverseSurface = Color(0xFFF4F7FB),
        onBackground = Color(0xFFF4F7FB),
        onDanger = Color(0xFF0C1422),
        onDangerSubtle = Color(0xFFFDEDEC),
        onInverseSurface = Color(0xFF0C1422),
        onPrimary = Color(0xFF0C1422),
        onPrimarySubtle = Color(0xFFDCE3FF),
        onSelection = Color(0xFFFFFFFF),
        onSuccess = Color(0xFF0C1422),
        onSuccessSubtle = Color(0xFFEAF8EF),
        onSurface = Color(0xFFF4F7FB),
        onSurfaceMuted = Color(0xFFB8C5D6),
        onWarning = Color(0xFF0C1422),
        onWarningSubtle = Color(0xFFFFF7E1),
        pressed = Color(0xFF35455C),
        primary = Color(0xFFA9B9FF),
        primaryHover = Color(0xFFC4D0FF),
        primaryPressed = Color(0xFFDCE3FF),
        primarySubtle = Color(0xFF28439F),
        scrim = Color(0xB3000000),
        selection = Color(0xFF28439F),
        success = Color(0xFFA3D9B7),
        successSubtle = Color(0xFF0B5132),
        surface = Color(0xFF162238),
        surfaceInset = Color(0xFF0C1422),
        surfaceRaised = Color(0xFF233146),
        tableAlternateRow = Color(0xFF233146),
        warning = Color(0xFFF9D88C),
        warningSubtle = Color(0xFF6D4500),
    )
    val dark = BraceColorScheme(
        semantic = darkSemantic,
        components = buildBraceComponentColors(darkSemantic),
    )

    private val highContrastLightSemantic = BraceSemanticColors(
        background = Color(0xFFFFFFFF),
        border = Color(0xFF35455C),
        borderStrong = Color(0xFF000000),
        danger = Color(0xFF8C1A16),
        dangerHover = Color(0xFFB3261E),
        dangerPressed = Color(0xFF701511),
        dangerSubtle = Color(0xFFFDEDEC),
        disabledContainer = Color(0xFFE9EEF5),
        disabledContent = Color(0xFF35455C),
        focusRing = Color(0xFF17368D),
        hover = Color(0xFFE9EEF5),
        inverseSurface = Color(0xFF000000),
        onBackground = Color(0xFF000000),
        onDanger = Color(0xFFFFFFFF),
        onDangerSubtle = Color(0xFF8C1A16),
        onInverseSurface = Color(0xFFFFFFFF),
        onPrimary = Color(0xFFFFFFFF),
        onPrimarySubtle = Color(0xFF17368D),
        onSelection = Color(0xFF000000),
        onSuccess = Color(0xFFFFFFFF),
        onSuccessSubtle = Color(0xFF0B5132),
        onSurface = Color(0xFF000000),
        onSurfaceMuted = Color(0xFF233146),
        onWarning = Color(0xFFFFFFFF),
        onWarningSubtle = Color(0xFF6D4500),
        pressed = Color(0xFFD5DEEA),
        primary = Color(0xFF17368D),
        primaryHover = Color(0xFF28439F),
        primaryPressed = Color(0xFF3654C6),
        primarySubtle = Color(0xFFEBEFFF),
        scrim = Color(0xB3000000),
        selection = Color(0xFFC4D0FF),
        success = Color(0xFF0B5132),
        successSubtle = Color(0xFFEAF8EF),
        surface = Color(0xFFFFFFFF),
        surfaceInset = Color(0xFFF4F7FB),
        surfaceRaised = Color(0xFFFFFFFF),
        tableAlternateRow = Color(0xFFF4F7FB),
        warning = Color(0xFF6D4500),
        warningSubtle = Color(0xFFFFF7E1),
    )
    val highContrastLight = BraceColorScheme(
        semantic = highContrastLightSemantic,
        components = buildBraceComponentColors(highContrastLightSemantic),
    )

    private val highContrastDarkSemantic = BraceSemanticColors(
        background = Color(0xFF000000),
        border = Color(0xFFB8C5D6),
        borderStrong = Color(0xFFFFFFFF),
        danger = Color(0xFFF5B2AA),
        dangerHover = Color(0xFFFAD3D0),
        dangerPressed = Color(0xFFFDEDEC),
        dangerSubtle = Color(0xFF8C1A16),
        disabledContainer = Color(0xFF162238),
        disabledContent = Color(0xFFD5DEEA),
        focusRing = Color(0xFFC4D0FF),
        hover = Color(0xFF233146),
        inverseSurface = Color(0xFFFFFFFF),
        onBackground = Color(0xFFFFFFFF),
        onDanger = Color(0xFF000000),
        onDangerSubtle = Color(0xFFFFFFFF),
        onInverseSurface = Color(0xFF000000),
        onPrimary = Color(0xFF000000),
        onPrimarySubtle = Color(0xFFFFFFFF),
        onSelection = Color(0xFFFFFFFF),
        onSuccess = Color(0xFF000000),
        onSuccessSubtle = Color(0xFFFFFFFF),
        onSurface = Color(0xFFFFFFFF),
        onSurfaceMuted = Color(0xFFD5DEEA),
        onWarning = Color(0xFF000000),
        onWarningSubtle = Color(0xFFFFFFFF),
        pressed = Color(0xFF35455C),
        primary = Color(0xFFC4D0FF),
        primaryHover = Color(0xFFDCE3FF),
        primaryPressed = Color(0xFFFFFFFF),
        primarySubtle = Color(0xFF28439F),
        scrim = Color(0xCC000000),
        selection = Color(0xFF28439F),
        success = Color(0xFFA3D9B7),
        successSubtle = Color(0xFF0B5132),
        surface = Color(0xFF000000),
        surfaceInset = Color(0xFF000000),
        surfaceRaised = Color(0xFF0C1422),
        tableAlternateRow = Color(0xFF0C1422),
        warning = Color(0xFFF9D88C),
        warningSubtle = Color(0xFF6D4500),
    )
    val highContrastDark = BraceColorScheme(
        semantic = highContrastDarkSemantic,
        components = buildBraceComponentColors(highContrastDarkSemantic),
    )

    val spacing = BraceSpacingTokens(
        lg = 16.dp,
        md = 12.dp,
        none = 0.dp,
        sm = 8.dp,
        xl = 24.dp,
        xs = 4.dp,
        xxl = 32.dp,
        xxs = 2.dp,
        xxxl = 48.dp,
    )

    val sizing = BraceSizingTokens(
        borderStrongWidth = 2.dp,
        borderWidth = 1.dp,
        focusRingWidth = 2.dp,
        iconLg = 24.dp,
        iconMd = 20.dp,
        iconSm = 16.dp,
        overlayMaxWidth = 560.dp,
        tableMinColumnWidth = 72.dp,
        touchTarget = 48.dp,
    )

    val shape = BraceShapeTokens(
        lg = 12.dp,
        md = 8.dp,
        none = 0.dp,
        pill = 999.dp,
        sm = 5.dp,
        xs = 3.dp,
    )

    val elevation = BraceElevationTokens(
        floating = 8.dp,
        modal = 16.dp,
        none = 0.dp,
        raised = 2.dp,
    )

    val motion = BraceMotionTokens(
        fast = 100,
        instant = 0,
        normal = 180,
        slow = 280,
    )

    val compact = BraceDensityTokens(
        contentPaddingDp = 8.dp,
        controlHeightDp = 32.dp,
        itemGapDp = 4.dp,
        rowHeightDp = 36.dp,
    )

    val comfortable = BraceDensityTokens(
        contentPaddingDp = 12.dp,
        controlHeightDp = 40.dp,
        itemGapDp = 8.dp,
        rowHeightDp = 48.dp,
    )

    val componentMetrics = BraceComponentMetrics(
        button = BraceButtonMetrics(
            cornerRadius = 5.dp,
            horizontalPadding = 12.dp,
            iconGap = 8.dp,
        ),
        callout = BraceCalloutMetrics(
            accentWidth = 3.dp,
            contentPadding = 16.dp,
            cornerRadius = 8.dp,
        ),
        card = BraceCardMetrics(
            contentPadding = 16.dp,
            cornerRadius = 8.dp,
        ),
        checkbox = BraceCheckboxMetrics(
            cornerRadius = 4.dp,
            focusCornerRadius = 6.dp,
            size = 20.dp,
            strokeWidth = 2.dp,
        ),
        controlCard = BraceControlCardMetrics(
            contentPadding = 16.dp,
            cornerRadius = 8.dp,
            descriptionGap = 2.dp,
            indicatorGap = 12.dp,
            radioDotRadius = 5.dp,
            radioSize = 20.dp,
            radioStrokeWidth = 2.dp,
        ),
        dateInput = BraceDateInputMetrics(
            borderWidth = 1.dp,
            cornerRadius = 5.dp,
            horizontalPadding = 10.dp,
        ),
        datePicker = BraceDatePickerMetrics(
            columnGap = 0.dp,
            contentPadding = 8.dp,
            cornerRadius = 5.dp,
            daySize = 48.dp,
        ),
        dateRangeInput = BraceDateRangeInputMetrics(
            borderWidth = 1.dp,
            cornerRadius = 5.dp,
            fieldGap = 8.dp,
            horizontalPadding = 10.dp,
        ),
        dateRangePicker = BraceDateRangePickerMetrics(
            columnGap = 0.dp,
            contentPadding = 8.dp,
            cornerRadius = 5.dp,
            daySize = 48.dp,
            monthGap = 16.dp,
            twoMonthMinWidth = 720.dp,
        ),
        dialog = BraceDialogMetrics(
            contentPadding = 24.dp,
            cornerRadius = 12.dp,
        ),
        drawer = BraceDrawerMetrics(
            contentPadding = 24.dp,
            cornerRadius = 12.dp,
            maxWidth = 420.dp,
        ),
        entityTitle = BraceEntityTitleMetrics(
            iconGap = 12.dp,
            iconSize = 24.dp,
            loadingCornerRadius = 3.dp,
            loadingSubtitleHeight = 12.dp,
            loadingSubtitleWidth = 104.dp,
            loadingTitleHeight = 20.dp,
            loadingTitleWidth = 160.dp,
            subtitleGap = 4.dp,
            titleTagsGap = 8.dp,
        ),
        input = BraceInputMetrics(
            borderWidth = 1.dp,
            cornerRadius = 5.dp,
            horizontalPadding = 10.dp,
        ),
        menu = BraceMenuMetrics(
            cornerRadius = 8.dp,
            itemHorizontalPadding = 12.dp,
        ),
        panelStack = BracePanelStackMetrics(
            backMaxWidth = 144.dp,
            horizontalPadding = 12.dp,
            itemGap = 8.dp,
            minHeight = 56.dp,
            verticalPadding = 4.dp,
        ),
        popover = BracePopoverMetrics(
            contentPadding = 12.dp,
            cornerRadius = 8.dp,
            maxWidth = 360.dp,
        ),
        progress = BraceProgressMetrics(
            cornerRadius = 999.dp,
            trackHeight = 6.dp,
        ),
        radio = BraceRadioMetrics(
            dotRadius = 5.dp,
            size = 20.dp,
            strokeWidth = 2.dp,
        ),
        segmentedControl = BraceSegmentedControlMetrics(
            cornerRadius = 6.dp,
            gap = 2.dp,
            horizontalPadding = 12.dp,
            itemCornerRadius = 4.dp,
        ),
        select = BraceSelectMetrics(
            cornerRadius = 5.dp,
            maxListHeight = 280.dp,
            minWidth = 240.dp,
            optionHorizontalPadding = 12.dp,
            searchHorizontalPadding = 10.dp,
        ),
        shortcut = BraceShortcutMetrics(
            cornerRadius = 4.dp,
            horizontalPadding = 6.dp,
            verticalPadding = 2.dp,
        ),
        skeleton = BraceSkeletonMetrics(
            cornerRadius = 4.dp,
            lineHeight = 16.dp,
        ),
        slider = BraceSliderMetrics(
            axisLabelGap = 4.dp,
            focusCornerRadius = 8.dp,
            minHeight = 48.dp,
            thumbHeight = 24.dp,
            thumbSlotWidth = 28.dp,
            thumbWidth = 16.dp,
        ),
        spinner = BraceSpinnerMetrics(
            largeSize = 48.dp,
            mediumSize = 32.dp,
            smallSize = 20.dp,
            strokeWidth = 3.dp,
        ),
        switch = BraceSwitchMetrics(
            focusCornerRadius = 6.dp,
            thumbInset = 3.dp,
            thumbRadius = 8.dp,
            trackHeight = 22.dp,
            trackWidth = 38.dp,
        ),
        table = BraceTableMetrics(
            cellHorizontalPadding = 12.dp,
            gridLineWidth = 1.dp,
            resizeHandleWidth = 4.dp,
        ),
        tag = BraceTagMetrics(
            cornerRadius = 3.dp,
            horizontalPadding = 6.dp,
        ),
        timeInput = BraceTimeInputMetrics(
            borderWidth = 1.dp,
            cornerRadius = 5.dp,
            horizontalPadding = 10.dp,
        ),
        timePicker = BraceTimePickerMetrics(
            borderWidth = 1.dp,
            columnGap = 8.dp,
            contentPadding = 8.dp,
            cornerRadius = 5.dp,
            unitWidth = 56.dp,
        ),
        timeZoneSelect = BraceTimeZoneSelectMetrics(
            cornerRadius = 5.dp,
            horizontalPadding = 10.dp,
            listMaxHeight = 320.dp,
            minWidth = 280.dp,
            rowHeight = 48.dp,
        ),
        toast = BraceToastMetrics(
            contentPadding = 12.dp,
            cornerRadius = 8.dp,
            iconGap = 8.dp,
            maxWidth = 440.dp,
        ),
        tooltip = BraceTooltipMetrics(
            contentPadding = 8.dp,
            cornerRadius = 5.dp,
            maxWidth = 280.dp,
        ),
        topBar = BraceTopBarMetrics(
            dividerHeight = 24.dp,
            groupGap = 8.dp,
            horizontalPadding = 16.dp,
            minHeight = 56.dp,
            verticalPadding = 4.dp,
        ),
        tree = BraceTreeMetrics(
            cornerRadius = 5.dp,
            horizontalPadding = 8.dp,
            indent = 16.dp,
        ),
    )

    val typeScale = BraceTypeScaleTokens(
        fontFamilies = BraceFontFamilyTokens(
            body = FontFamily.SansSerif,
            mono = FontFamily.Monospace,
        ),
        fontSizes = BraceFontSizeTokens(
            lg = 16.sp,
            md = 14.sp,
            sm = 12.sp,
            xl = 20.sp,
            xs = 11.sp,
            xxl = 28.sp,
        ),
        lineHeights = BraceLineHeightTokens(
            display = 34.sp,
            normal = 20.sp,
            relaxed = 24.sp,
            tight = 16.sp,
        ),
        weights = BraceFontWeightTokens(
            bold = FontWeight.W700,
            medium = FontWeight.W500,
            regular = FontWeight.W400,
            semibold = FontWeight.W600,
        ),
    )

    val typography = BraceTypographyTokens(
        body = TextStyle(
            fontFamily = FontFamily.SansSerif,
            fontSize = 14.sp,
            lineHeight = 20.sp,
            fontWeight = FontWeight.W400,
        ),
        bodyStrong = TextStyle(
            fontFamily = FontFamily.SansSerif,
            fontSize = 14.sp,
            lineHeight = 20.sp,
            fontWeight = FontWeight.W600,
        ),
        caption = TextStyle(
            fontFamily = FontFamily.SansSerif,
            fontSize = 11.sp,
            lineHeight = 16.sp,
            fontWeight = FontWeight.W400,
        ),
        code = TextStyle(
            fontFamily = FontFamily.Monospace,
            fontSize = 12.sp,
            lineHeight = 20.sp,
            fontWeight = FontWeight.W400,
        ),
        display = TextStyle(
            fontFamily = FontFamily.SansSerif,
            fontSize = 28.sp,
            lineHeight = 34.sp,
            fontWeight = FontWeight.W700,
        ),
        label = TextStyle(
            fontFamily = FontFamily.SansSerif,
            fontSize = 12.sp,
            lineHeight = 16.sp,
            fontWeight = FontWeight.W600,
        ),
        subtitle = TextStyle(
            fontFamily = FontFamily.SansSerif,
            fontSize = 16.sp,
            lineHeight = 24.sp,
            fontWeight = FontWeight.W600,
        ),
        title = TextStyle(
            fontFamily = FontFamily.SansSerif,
            fontSize = 20.sp,
            lineHeight = 24.sp,
            fontWeight = FontWeight.W600,
        ),
    )
}
